import { svgImport } from "@/utils/common/svg-helper";
import PHArrowClockwiseData from "@phosphor-icons/core/bold/arrow-clockwise-bold.svg";
import PHCaretDownData from "@phosphor-icons/core/regular/caret-down.svg";
import PHDotsSixData from "@phosphor-icons/core/regular/dots-six.svg";
import PHEyeData from "@phosphor-icons/core/regular/eye.svg";
import PHEyeSlashData from "@phosphor-icons/core/regular/eye-slash.svg";
import PHPlusData from "@phosphor-icons/core/regular/plus.svg";
import PHTrashData from "@phosphor-icons/core/regular/trash.svg";
import PHQuestionData from "@phosphor-icons/core/regular/question.svg";
import PHXData from "@phosphor-icons/core/regular/x.svg";
import PHXCircleData from "@phosphor-icons/core/regular/x-circle.svg";
import PHBoldArrowDownData from "@phosphor-icons/core/bold/arrow-down-bold.svg";
import PHBoldArrowUpData from "@phosphor-icons/core/bold/arrow-up-bold.svg";
import PHBoldCheckData from "@phosphor-icons/core/bold/check-bold.svg";
import PHBoldCheckCircleData from "@phosphor-icons/core/bold/check-circle-bold.svg";
import PHBoldCopyData from "@phosphor-icons/core/bold/copy-bold.svg";
import PHBoldInfoData from "@phosphor-icons/core/bold/info-bold.svg";
import PHBoldSpinnerGapData from "@phosphor-icons/core/bold/spinner-gap-bold.svg";
import PHBoldWarningCircleData from "@phosphor-icons/core/bold/warning-circle-bold.svg";
import PHBoldXCircleData from "@phosphor-icons/core/bold/x-circle-bold.svg";
import PHFillAirplaneData from "@phosphor-icons/core/fill/airplane-fill.svg";
import PHFillArrowsOutCardinalData from "@phosphor-icons/core/fill/arrows-out-cardinal-fill.svg";
import PHFillBellData from "@phosphor-icons/core/fill/bell-fill.svg";
import PHFillBellSlashData from "@phosphor-icons/core/fill/bell-slash-fill.svg";
import PHFillCaretDownData from "@phosphor-icons/core/fill/caret-down-fill.svg";
import PHFillCaretRightData from "@phosphor-icons/core/fill/caret-right-fill.svg";
import PHFillCaretUpData from "@phosphor-icons/core/fill/caret-up-fill.svg";
import PHFillInfoData from "@phosphor-icons/core/fill/info-fill.svg";
import PHFillGearData from "@phosphor-icons/core/fill/gear-fill.svg";
import PHFillPlusData from "@phosphor-icons/core/fill/plus-fill.svg";
import PHFillStethoscopeData from "@phosphor-icons/core/fill/stethoscope-fill.svg";
import PHFillTableData from "@phosphor-icons/core/fill/table-fill.svg";

export const PHArrowClockwise = svgImport(PHArrowClockwiseData);
export const PHCaretDown = svgImport(PHCaretDownData);
export const PHDotsSix = svgImport(PHDotsSixData);
export const PHEye = svgImport(PHEyeData);
export const PHEyeSlash = svgImport(PHEyeSlashData);
export const PHPlus = svgImport(PHPlusData);
export const PHTrash = svgImport(PHTrashData);
export const PHQuestion = svgImport(PHQuestionData);
export const PHX = svgImport(PHXData);
export const PHXCircle = svgImport(PHXCircleData);

export const PHBoldArrowDown = svgImport(PHBoldArrowDownData);
export const PHBoldArrowUp = svgImport(PHBoldArrowUpData);
export const PHBoldCheck = svgImport(PHBoldCheckData);
export const PHBoldCheckCircle = svgImport(PHBoldCheckCircleData);
export const PHBoldCopy = svgImport(PHBoldCopyData);
export const PHBoldInfo = svgImport(PHBoldInfoData);
export const PHBoldWarningCircle = svgImport(PHBoldWarningCircleData);
export const PHBoldXCircle = svgImport(PHBoldXCircleData);
export const PHBoldSpinnerGap = svgImport(PHBoldSpinnerGapData);

export const PHFillArrowsOutCardinal = svgImport(PHFillArrowsOutCardinalData);
export const PHFillAirplane = svgImport(PHFillAirplaneData);
export const PHFillBell = svgImport(PHFillBellData);
export const PHFillBellSlash = svgImport(PHFillBellSlashData);
export const PHFillCaretDown = svgImport(PHFillCaretDownData);
export const PHFillCaretRight = svgImport(PHFillCaretRightData);
export const PHFillCaretUp = svgImport(PHFillCaretUpData);
export const PHFillInfo = svgImport(PHFillInfoData);
export const PHFillGear = svgImport(PHFillGearData);
export const PHFillPlus = svgImport(PHFillPlusData);
export const PHFillStethoscope = svgImport(PHFillStethoscopeData);
export const PHFillTable = svgImport(PHFillTableData);
