import type { PreferenceStoragePath } from "@/entrypoints/options/components/preferences/preference-storage";
import type { PreferenceGroupId } from "./configuration";

export interface SearchablePreference {
	path: PreferenceStoragePath;
	label: string;
	description?: string;
	keywords?: string[];
	group: PreferenceGroupId;
	section: string;
}

export function getLastKey(path: string): string {
	const parts = path.split(".");
	return parts[parts.length - 1];
}

export const PREFERENCE_SEARCH_DATA: readonly SearchablePreference[] = [
	/*
	 * Internal
	 */
	// Section: internal
	{ path: "settings.themes.pages", label: "Page Theme", group: "internal", section: "internal", keywords: ["dark", "light", "os"] },

	// Section: popup
	{ path: "settings.pages.popup.dashboard", label: "Popup: Dashboard", group: "internal", section: "popup" },
	{ path: "settings.pages.popup.marketSearch", label: "Popup: Market search", group: "internal", section: "popup", keywords: ["bazaar", "item market"] },
	{ path: "settings.pages.popup.calculator", label: "Popup: Calculator", group: "internal", section: "popup" },
	{ path: "settings.pages.popup.stocksOverview", label: "Popup: Stocks overview", group: "internal", section: "popup" },
	{ path: "settings.pages.popup.notifications", label: "Popup: Notifications", group: "internal", section: "popup" },
	{ path: "settings.pages.popup.defaultTab", label: "Default tab", group: "internal", section: "popup" },
	{ path: "settings.pages.popup.showStakeouts", label: "Show stakeouts", group: "internal", section: "popup" },
	{ path: "settings.pages.popup.showIcons", label: "Show status icons", group: "internal", section: "popup" },
	{ path: "settings.pages.popup.fullBarTime", label: "Show bar full time", group: "internal", section: "popup", keywords: ["energy", "nerve"] },
	{ path: "settings.pages.popup.bazaarUsingExternal", label: "Populate bazaar prices using external services", group: "internal", section: "popup" },
	{ path: "settings.pages.icon.global", label: "Enable icon bars", group: "internal", section: "popup" },
	{ path: "settings.pages.icon.energy", label: "Icon bars: Energy", group: "internal", section: "popup" },
	{ path: "settings.pages.icon.nerve", label: "Icon bars: Nerve", group: "internal", section: "popup" },
	{ path: "settings.pages.icon.happy", label: "Icon bars: Happy", group: "internal", section: "popup" },
	{ path: "settings.pages.icon.life", label: "Icon bars: Life", group: "internal", section: "popup" },
	{ path: "settings.pages.icon.chain", label: "Icon bars: Chain", group: "internal", section: "popup" },
	{ path: "settings.pages.icon.travel", label: "Icon bars: Travel", group: "internal", section: "popup" },

	// Section: Notifications
	{ path: "settings.notifications.types.global", label: "Overall Notifications", group: "internal", section: "notifications" },
	{ path: "settings.notifications.link", label: "Open related page when clicking a notification", group: "internal", section: "notifications" },
	{ path: "settings.notifications.requireInteraction", label: "Require interaction for notifications", group: "internal", section: "notifications" },
	{ path: "settings.notifications.sound", label: "Sound effect", group: "internal", section: "notifications", keywords: ["custom"] },
	{ path: "settings.notifications.volume", label: "Sound volume", group: "internal", section: "notifications" },
	{ path: "settings.notifications.tts", label: "Text-to-speech", group: "internal", section: "notifications" },
	{ path: "settings.notifications.ttsRate", label: "Speech rate", group: "internal", section: "notifications", keywords: ["text", "text-to-speech"] },
	{ path: "settings.notifications.ttsVoice", label: "TTS Voice", group: "internal", section: "notifications", keywords: ["text", "text-to-speech"] },
	{ path: "settings.notifications.types.events", label: "Notification: Events", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.messages", label: "Notification: Messages", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.status", label: "Notification: Status change", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.traveling", label: "Notification: Traveling", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.education", label: "Notification: Education", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.newDay", label: "Notification: New day", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.offline", label: "Notification: Offline hours", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.leavingHospitalEnabled", label: "Notification: Leaving hospital", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.landingEnabled", label: "Notification: Landing", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.energy", label: "Notification: Energy", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.nerve", label: "Notification: Nerve", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.happy", label: "Notification: Happy", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.life", label: "Notification: Life", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.refillEnergy", label: "Notification: Energy refill", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.refillNerveEnabled", label: "Notification: Nerve refill", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.cooldowns", label: "Notification: Cooldowns", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.cooldownDrugEnabled", label: "Notification: Drug cooldown", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.cooldownBoosterEnabled", label: "Notification: Booster cooldown", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.cooldownMedicalEnabled", label: "Notification: Medical cooldown", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.missionsExpireEnabled", label: "Notification: Missions expiry", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.missionsLimitEnabled", label: "Notification: Missions limit", group: "internal", section: "notifications" },
	{
		path: "settings.notifications.types.chainTimerEnabled",
		label: "Notification: Chain timer",
		group: "internal",
		section: "notifications",
		keywords: ["faction"],
	},
	{
		path: "settings.notifications.types.chainBonusEnabled",
		label: "Notification: Chain bonus",
		group: "internal",
		section: "notifications",
		keywords: ["faction"],
	},
	{
		path: "settings.notifications.types.npcsGlobal",
		label: "Notification: NPCs enabled",
		group: "internal",
		section: "notifications",
		keywords: ["faction"],
	},
	{ path: "settings.notifications.types.npcs", label: "Notification: NPCs", group: "internal", section: "notifications" },
	{ path: "settings.notifications.types.npcPlannedEnabled", label: "Notification: Planned NPC attack", group: "internal", section: "notifications" },
	{ path: "api.torn.key", label: "API key", group: "internal", section: "api" },
	{ path: "settings.apiUsage.comment", label: "API comment", group: "internal", section: "api" },
	{ path: "settings.apiUsage.delayEssential", label: "API Usage: essential userdata interval", group: "internal", section: "api" },
	{ path: "settings.apiUsage.delayBasic", label: "API Usage: basic userdata interval", group: "internal", section: "api" },
	{ path: "settings.apiUsage.delayPassive", label: "API Usage: passive userdata interval", group: "internal", section: "api" },
	{ path: "settings.apiUsage.delayStakeouts", label: "API Usage: stakeout interval", group: "internal", section: "api" },

	/*
	 * Global
	 */
	// Section: global
	{ path: "settings.themes.containers", label: "Container Theme", group: "global", section: "global", keywords: ["dark", "light"] },
	{ path: "settings.csvDelimiter", label: "CSV Delimiter", group: "global", section: "global" },
	{ path: "settings.formatting.date", label: "Date Format", group: "global", section: "global" },
	{ path: "settings.formatting.time", label: "Time Format", group: "global", section: "global", keywords: ["12h", "24h"] },
	{ path: "settings.formatting.tct", label: "Show times in TCT", group: "global", section: "global" },
	{ path: "settings.pages.global.alignLeft", label: "Align left", group: "global", section: "global" },
	{ path: "settings.pages.global.keepAttackHistory", label: "Keep attack history", group: "global", section: "global", keywords: ["attacks"] },
	{ path: "settings.pages.global.hideLevelUpgrade", label: "Hide level upgrade", group: "global", section: "global" },
	{ path: "settings.pages.global.hideTutorials", label: "Hide tutorials", group: "global", section: "global" },
	{ path: "settings.pages.global.hideQuitButtons", label: "Hide leave and quit buttons", group: "global", section: "global" },
	{ path: "settings.pages.global.miniProfileLastAction", label: "Last action in mini profile", group: "global", section: "global" },
	{ path: "settings.pages.global.stackingMode", label: "Stacking mode", group: "global", section: "global" },
	{ path: "settings.pages.global.noOutsideLinkAlert", label: "No outside link alert", group: "global", section: "global", keywords: ["external links"] },
	{ path: "settings.pages.global.pageTitles", label: "Clearer page titles", group: "global", section: "global" },
	{ path: "settings.pages.global.urlFill", label: "URL Fill", group: "global", section: "global" },
	{ path: "settings.pages.competitions.easterEggs", label: "Highlight Easter Eggs", group: "global", section: "global", keywords: ["event"] },
	{ path: "settings.pages.competitions.easterEggsAlert", label: "Highlight Easter Eggs alert", group: "global", section: "global" },
	{ path: "settings.pages.global.reviveProvider", label: "Revive Provider", group: "global", section: "global" },

	// Section: sidebar
	{ path: "settings.pages.sidebar.notes", label: "Sidebar notes", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.companyAddictionLevel", label: "Company addiction level", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.showJobPointsToolTip", label: "Job points tooltip", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.barLinks", label: "Make the energy and nerve bar link to a related page", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.highlightEnergy", label: "Highlight energy when refill is unused", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.highlightNerve", label: "Highlight nerve when refill is unused", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.pointsValue", label: "Points value", group: "global", section: "sidebar" },
	{ path: "settings.updateNotice", label: "Extension update notice", group: "global", section: "sidebar" },
	{ path: "settings.scripts.achievements.show", label: "Display achievements", group: "global", section: "sidebar" },
	{ path: "settings.scripts.achievements.completed", label: "Show completed achievements", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.ocTimer", label: "OC 1.0 ready time", group: "global", section: "sidebar", keywords: ["organized crime"] },
	{ path: "settings.pages.sidebar.oc2Timer", label: "OC 2.0 ready time", group: "global", section: "sidebar", keywords: ["organized crime"] },
	{ path: "settings.pages.sidebar.oc2TimerLevel", label: "OC 2.0 include crime level", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.oc2TimerPosition", label: "OC 2.0 include crime name and position", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.factionOCTimer", label: "Faction OC 1.0 ready time", group: "global", section: "sidebar", keywords: ["organized crime"] },
	{ path: "settings.pages.sidebar.cooldownEndTimes", label: "Cooldown end times", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.rwTimer", label: "Ranked war timer", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.virusTimer", label: "Virus timer", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.collapseAreas", label: "Collapsible areas", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.settingsLink", label: "TT settings link", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.hideGymHighlight", label: "Hide gym highlight", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.hideNewspaperHighlight", label: "Hide newspaper highlight", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.upkeepPropHighlight", label: "Property upkeep highlight", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.npcLootTimes", label: "NPC loot times", group: "global", section: "sidebar" },
	{ path: "settings.pages.sidebar.npcLootTimesService", label: "NPC loot source", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.show", label: "Display reminders", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.finished", label: "Include reminders with finished tasks", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.energyRefill", label: "Reminders: Energy Refill", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.nerveRefill", label: "Reminders: Nerve Refill", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.medicalCooldown", label: "Reminders: Medical Cooldown", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.boosterCooldown", label: "Reminders: Booster Cooldown", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.drugCooldown", label: "Reminders: Drug Cooldown", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.bankInvestment", label: "Reminders: Bank Investment", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.virusCoding", label: "Reminders: Virus Coding", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.missionReward", label: "Reminders: Mission Reward", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.oc", label: "Reminders: OC", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.ocItem", label: "Reminders: OC Item", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.race", label: "Reminders: Race", group: "global", section: "sidebar" },
	{ path: "settings.scripts.reminders.types.education", label: "Reminders: Education", group: "global", section: "sidebar" },

	// Section: chat
	{ path: "settings.pages.chat.fontSize", label: "Font size", group: "global", section: "chat" },
	{ path: "settings.pages.chat.searchChat", label: "Search chat", group: "global", section: "chat" },
	{ path: "settings.pages.chat.completeUsernames", label: "Autocomplete usernames", group: "global", section: "chat" },
	{ path: "settings.pages.chat.tradeTimer", label: "Trade chat timer till next post", group: "global", section: "chat" },
	{ path: "settings.pages.chat.hideChatButton", label: "Button for hiding chat", group: "global", section: "chat" },
	{ path: "settings.pages.chat.resizable", label: "Make chats resizable", group: "global", section: "chat" },

	// Section: advanced
	{ path: "settings.developer", label: "Developer errors", group: "global", section: "advanced" },
	{ path: "settings.featureDisplay", label: "Feature manager", group: "global", section: "advanced" },
	{ path: "settings.featureDisplayOnlyFailed", label: "Feature manager: only failed", group: "global", section: "advanced" },
	{ path: "settings.featureDisplayHideDisabled", label: "Feature manager: hide disabled", group: "global", section: "advanced" },
	{ path: "settings.featureDisplayHideEmpty", label: "Feature manager: hide when empty", group: "global", section: "advanced" },

	/*
	 * Financial
	 */
	// Section: money
	{
		path: "settings.pages.events.worth",
		label: "Show worth of points, bazaar sales and item market sales on event hover",
		group: "financial",
		section: "money",
		keywords: ["events"],
	},
	{ path: "settings.pages.home.networthDetails", label: "Display networth details on the homepage", group: "financial", section: "money" },
	{ path: "settings.pages.trade.itemValues", label: "Trade item value", group: "financial", section: "money" },
	{ path: "settings.pages.displayCase.worth", label: "Display case worth", group: "financial", section: "money" },
	{ path: "settings.pages.crimes2.value", label: "Total value for your crimes v2 item rewards", group: "financial", section: "money" },
	{ path: "settings.pages.items.values", label: "Display item values", group: "financial", section: "money" },
	{ path: "settings.pages.items.marketLinks", label: "Link to the item market", group: "financial", section: "money" },
	{ path: "settings.pages.items.openedSupplyPackValue", label: "Total value of items for supply pack", group: "financial", section: "money" },
	{ path: "settings.pages.bank.investmentInfo", label: "Enable bank investment info", group: "financial", section: "money" },
	{ path: "settings.pages.bank.investmentDueTime", label: "Enable bank investment due time", group: "financial", section: "money" },
	{ path: "settings.pages.stocks.acronyms", label: "Display acronyms beside stock names", group: "financial", section: "money", keywords: ["stocks"] },
	{
		path: "settings.pages.stocks.moneyInput",
		label: "Display money input when buying and selling stock",
		group: "financial",
		section: "money",
		keywords: ["stocks"],
	},
	{
		path: "settings.pages.stocks.valueAndProfit",
		label: "Display total value of portfolio and profits",
		group: "financial",
		section: "money",
		keywords: ["stocks"],
	},
	{ path: "settings.pages.casino.netTotal", label: "Show net total of casino game", group: "financial", section: "money" },
	{ path: "settings.pages.casino.blackjack", label: "Show the optimal choice for blackjack", group: "financial", section: "money", keywords: ["casino"] },
	{ path: "settings.pages.casino.highlow", label: "Enable the high-low helper", group: "financial", section: "money", keywords: ["casino"] },
	{ path: "settings.pages.casino.highlowMovement", label: "Move high-low buttons to make it easier to click through", group: "financial", section: "money" },

	// Section: markets
	{ path: "settings.pages.bazaar.itemsCost", label: "Show the total cost of buying an item", group: "financial", section: "markets", keywords: ["bazaar"] },
	{ path: "settings.pages.bazaar.worth", label: "Show the worth of the visited bazaar", group: "financial", section: "markets" },
	{ path: "settings.pages.bazaar.fillMax", label: "Bazaar Fill Max", group: "financial", section: "markets" },
	{ path: "settings.pages.bazaar.maxBuyIgnoreCash", label: "Bazaar Fill Max ignore cash on hand", group: "financial", section: "markets" },
	{
		path: "settings.pages.bazaar.highlightSubVendorItems",
		label: "Highlight items less than the vendor sell price",
		group: "financial",
		section: "markets",
		keywords: ["bazaar"],
	},
	{ path: "settings.pages.shops.fillMax", label: "Shop Fill Max", group: "financial", section: "markets", keywords: ["shops"] },
	{ path: "settings.pages.shops.maxBuyIgnoreCash", label: "Shop Fill Max ignore cash on hand", group: "financial", section: "markets" },
	{ path: "settings.pages.shops.profit", label: "Shop item profits", group: "financial", section: "markets", keywords: ["shops"] },
	{ path: "settings.pages.shops.values", label: "Shop item market values", group: "financial", section: "markets", keywords: ["shops"] },
	{ path: "settings.pages.itemmarket.highlightCheapItems", label: "Highlight item market items below value", group: "financial", section: "markets" },
	{
		path: "settings.pages.itemmarket.highlightCheapItemsSound",
		label: "Play a sound when highlighting cheap items",
		group: "financial",
		section: "markets",
		keywords: ["item market"],
	},
	{ path: "settings.pages.itemmarket.leftBar", label: "Move the market bar to the left", group: "financial", section: "markets", keywords: ["item market"] },
	{ path: "settings.pages.itemmarket.fillMax", label: "Item Market Fill Max", group: "financial", section: "markets" },
	{ path: "settings.pages.auction.movePagination", label: "Move pagination to the top of the list", group: "financial", section: "markets" },

	// Section: items
	{ path: "settings.pages.items.quickItems", label: "Show the quick items container", group: "financial", section: "items" },
	{ path: "settings.pages.items.drugDetails", label: "Show details about drugs", group: "financial", section: "items" },
	{ path: "settings.pages.items.highlightBloodBags", label: "Highlight blood bags", group: "financial", section: "items" },
	{ path: "settings.pages.items.energyWarning", label: "Warn if an item gives you energy over 1000", group: "financial", section: "items" },
	{ path: "settings.pages.items.medicalLife", label: "Show life information when consuming medical items", group: "financial", section: "items" },
	{ path: "settings.pages.items.hideRecycleMessage", label: "Hide the recycle message", group: "financial", section: "items" },
	{ path: "settings.pages.items.hideTooManyItemsWarning", label: "Hide the too many items warning", group: "financial", section: "items" },
	{ path: "settings.pages.items.missingBooks", label: "Display missing books", group: "financial", section: "items" },
	{ path: "settings.pages.items.missingFlowers", label: "Missing flowers", group: "financial", section: "items", keywords: ["museum"] },
	{ path: "settings.pages.items.missingPlushies", label: "Missing plushies", group: "financial", section: "items", keywords: ["museum"] },
	{ path: "settings.pages.items.bookEffects", label: "Book effects", group: "financial", section: "items", keywords: ["books"] },
	{ path: "settings.pages.items.canGains", label: "Energy drink gains", group: "financial", section: "items" },
	{ path: "settings.pages.items.candyHappyGains", label: "Candy happy gains", group: "financial", section: "items" },
	{ path: "settings.pages.items.nerveGains", label: "Alcohol nerve gains", group: "financial", section: "items" },

	/*
	 * QoL
	 */
	// Section: information
	{ path: "settings.pages.home.effectiveStats", label: "Show effective battle stats on the homepage", group: "qol", section: "information" },
	{ path: "settings.pages.city.items", label: "Highlight items on the city map", group: "qol", section: "information" },
	{ path: "settings.pages.city.combineDuplicates", label: "Combine duplicate city map items", group: "qol", section: "information" },
	{ path: "settings.scripts.lastAction.factionMember", label: "Last action: Faction members", group: "qol", section: "information" },
	{ path: "settings.scripts.lastAction.companyOwn", label: "Last action: Own company employees", group: "qol", section: "information" },
	{ path: "settings.scripts.lastAction.companyOther", label: "Last action: Other company employees", group: "qol", section: "information" },
	{ path: "settings.pages.property.value", label: "Show value of all properties", group: "qol", section: "information", keywords: ["property"] },
	{ path: "settings.pages.property.happy", label: "Show happiness of all properties", group: "qol", section: "information", keywords: ["property"] },
	{ path: "settings.pages.forums.menu", label: "Show forum action menu", group: "qol", section: "information" },
	{ path: "settings.pages.forums.debugInfoBtn", label: "Display button to add debugging information to forum thread", group: "qol", section: "information" },
	{
		path: "settings.pages.forums.onlyNewFeedButton",
		label: "Show a button to only show new items in a feed",
		group: "qol",
		section: "information",
		keywords: ["forum"],
	},
	{ path: "settings.pages.education.greyOut", label: "Grey out completed education categories", group: "qol", section: "information" },
	{ path: "settings.pages.education.finishTime", label: "Show education course finish time", group: "qol", section: "information" },
	{ path: "settings.pages.missions.hints", label: "Mission hints", group: "qol", section: "information", keywords: ["missions"] },
	{ path: "settings.pages.missions.rewards", label: "Mission reward information", group: "qol", section: "information", keywords: ["missions"] },
	{ path: "settings.pages.museum.autoFill", label: "Autofill number of sets in museum", group: "qol", section: "information" },
	{ path: "settings.pages.racing.winPercentage", label: "Show win percentage of each car", group: "qol", section: "information", keywords: ["racing"] },
	{ path: "settings.pages.racing.upgrades", label: "Show racing upgrade values", group: "qol", section: "information" },
	{ path: "settings.pages.api.autoDemo", label: "Automatically show demo content on API page", group: "qol", section: "information" },
	{ path: "settings.pages.api.autoFillKey", label: "Automatically fill your API key on API page", group: "qol", section: "information" },
	{
		path: "settings.pages.api.autoPretty",
		label: "Automatically select pretty outputs on API page",
		group: "qol",
		section: "information",
	},
	{ path: "settings.pages.api.clickableSelections", label: "Make API selections clickable", group: "qol", section: "information" },
	{ path: "settings.pages.stocks.filter", label: "Filter: Stocks", group: "qol", section: "information" },
	{ path: "settings.pages.auction.filter", label: "Filter: Auction House", group: "qol", section: "information" },
	{ path: "settings.pages.bounties.filter", label: "Filter: Bounties", group: "qol", section: "information" },
	{ path: "settings.pages.faction.armoryFilter", label: "Filter: Faction Armory", group: "qol", section: "information" },
	{ path: "settings.pages.faction.memberFilter", label: "Filter: Faction Members", group: "qol", section: "information" },
	{ path: "settings.pages.faction.rankedWarFilter", label: "Filter: Ranked War", group: "qol", section: "information", keywords: ["faction"] },
	{ path: "settings.pages.faction.oc2Filter", label: "Filter: OC2", group: "qol", section: "information", keywords: ["faction"] },
	{ path: "settings.pages.competition.filter", label: "Filter: Competition", group: "qol", section: "information" },
	{ path: "settings.pages.crimes2.burglaryFilter", label: "Filter: Burglary", group: "qol", section: "information", keywords: ["crimes"] },
	{ path: "settings.pages.friends.filter", label: "Filter: Friends", group: "qol", section: "information" },
	{ path: "settings.pages.enemies.filter", label: "Filter: Enemies", group: "qol", section: "information" },
	{ path: "settings.pages.targets.filter", label: "Filter: Targets", group: "qol", section: "information" },
	{ path: "settings.pages.hospital.filter", label: "Filter: Hospital", group: "qol", section: "information" },
	{ path: "settings.pages.jail.filter", label: "Filter: Jail", group: "qol", section: "information" },
	{ path: "settings.pages.racing.filter", label: "Filter: Custom Races", group: "qol", section: "information", keywords: ["racing"] },
	{ path: "settings.pages.shops.filters", label: "Filter: City Shops", group: "qol", section: "information" },
	{ path: "settings.pages.travel.itemFilter", label: "Filter: Travel Items", group: "qol", section: "information" },
	{ path: "settings.pages.travel.peopleFilter", label: "Filter: Abroad People", group: "qol", section: "information" },
	{ path: "settings.pages.userlist.filter", label: "Filter: Userlist", group: "qol", section: "information" },

	// Section: combat
	{
		path: "settings.scripts.ffScouter.miniProfile",
		label: "FF Scouter: Mini profiles",
		group: "qol",
		section: "combat",
		keywords: ["fair fight", "ffscouter", "ff-scouter"],
	},
	{
		path: "settings.scripts.ffScouter.profile",
		label: "FF Scouter: Profiles",
		group: "qol",
		section: "combat",
		keywords: ["fair fight", "ffscouter", "ff-scouter"],
	},
	{
		path: "settings.scripts.ffScouter.attack",
		label: "FF Scouter: Attack page",
		group: "qol",
		section: "combat",
		keywords: ["fair fight", "ffscouter", "ff-scouter"],
	},
	{
		path: "settings.scripts.ffScouter.factionList",
		label: "FF Scouter: Faction member lists",
		group: "qol",
		section: "combat",
		keywords: ["fair fight", "ffscouter", "ff-scouter"],
	},
	{
		path: "settings.scripts.ffScouter.gauge",
		label: "FF Scouter: Honor bars and name displays",
		group: "qol",
		section: "combat",
		keywords: ["fair fight", "ffscouter", "ff-scouter"],
	},
	{ path: "settings.pages.attack.timeoutWarning", label: "Play a sound when attack time drops below 30 seconds", group: "qol", section: "combat" },
	{
		path: "settings.pages.attack.fairAttack",
		label: "Show FF modifier",
		group: "qol",
		section: "combat",
		keywords: ["fair fight", "ffscouter", "ff-scouter"],
	},
	{ path: "settings.pages.attack.bonusInformation", label: "Show weapon bonus information in attack log", group: "qol", section: "combat" },
	{ path: "settings.pages.profile.showAllyWarning", label: "Show ally warning on profiles", group: "qol", section: "combat", keywords: ["friendly fire"] },
	{
		path: "settings.pages.profile.disableAllyAttacks",
		label: "Disable attack button on ally profile pages",
		group: "qol",
		section: "combat",
		keywords: ["friendly fire"],
	},
	{ path: "settings.scripts.statsEstimate.global", label: "Stats Estimate", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.maxLevel", label: "Stats Estimate: max level", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.delay", label: "Stats Estimate: delay requests", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.cachedOnly", label: "Stats Estimate: only show cached results", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.displayNoResult", label: "Stats Estimate: show notice when no cached result", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.profiles", label: "Stats Estimate: Profiles", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.enemies", label: "Stats Estimate: Enemies list", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.targets", label: "Stats Estimate: Targets list", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.hof", label: "Stats Estimate: Hall of Fame", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.attacks", label: "Stats Estimate: Attacks page", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.userlist", label: "Stats Estimate: Userlist", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.bounties", label: "Stats Estimate: Bounties", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.factions", label: "Stats Estimate: Faction members", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.wars", label: "Stats Estimate: Faction wars", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.rankedWars", label: "Stats Estimate: Faction ranked wars", group: "qol", section: "combat" },
	{ path: "settings.scripts.statsEstimate.abroad", label: "Stats Estimate: Abroad", group: "qol", section: "combat" },

	// Section: travel
	{ path: "settings.pages.travel.computer", label: "Show a computer link while flying or abroad", group: "qol", section: "travel" },
	{
		path: "settings.pages.travel.table",
		label: "Show a table of all countries with their item and stocks",
		group: "qol",
		section: "travel",
		keywords: ["travel table"],
	},
	{
		path: "settings.pages.travel.autoTravelTableCountry",
		label: "Update country in travel table filter as per map selections",
		group: "qol",
		section: "travel",
	},
	{ path: "settings.pages.travel.flyingTime", label: "Show the time when you would land when flying now", group: "qol", section: "travel" },
	{
		path: "settings.pages.travel.cooldownWarnings",
		label: "Show warnings if cooldowns will be over when you land back in Torn",
		group: "qol",
		section: "travel",
	},
	{ path: "settings.pages.travel.landingTime", label: "Show the landing time when flying", group: "qol", section: "travel" },
	{ path: "settings.pages.travel.cleanFlight", label: "Hide plane and funfact box while flying", group: "qol", section: "travel" },
	{ path: "settings.pages.travel.tabTitleTimer", label: "Show travel time in tab title", group: "qol", section: "travel" },
	{ path: "settings.pages.travel.travelProfits", label: "Show profits of items in market while abroad", group: "qol", section: "travel" },
	{ path: "settings.pages.travel.fillMax", label: "Show fill max button while abroad", group: "qol", section: "travel" },
	{ path: "settings.pages.travel.autoFillMax", label: "Automatically fill max amount of stock while abroad", group: "qol", section: "travel" },
	{ path: "settings.pages.travel.efficientRehab", label: "Efficiently rehab to not waste any natural decay", group: "qol", section: "travel" },
	{ path: "settings.pages.travel.efficientRehabSelect", label: "Automatically set rehab slider to the current amount", group: "qol", section: "travel" },

	// Section: faction
	{ path: "settings.pages.faction.idBesideFactionName", label: "Reformat faction names as FACTIONNAME [ID]", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.banker", label: "Show banker options", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.showFullInfobox", label: "Show full faction description without scroll bar", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.foldableInfobox", label: "Make faction infobox foldable", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.numberMembers", label: "Add numbers to every member of faction", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.warFinishTimes", label: "Show the finish time of wars", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.armoryWorth", label: "Show total worth of faction armory", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.upgradeRequiredRespect", label: "Show respect required for a faction upgrade", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.memberInfo", label: "Show money and points balance of members", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.quickItems", label: "Quick items in the armory", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.showFactionSpy", label: "Show spy details of faction members", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.totalChallengeContributions", label: "Show total challenge contributions", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.csvRankedWarReport", label: "CSV: Ranked war report", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.csvWarReport", label: "CSV: War report", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.csvChainReport", label: "CSV: Chain report", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.csvChallengeContributions", label: "CSV: Challenge contributions", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.highlightOwn", label: "Highlight own OC", group: "qol", section: "faction", keywords: ["organized crime"] },
	{ path: "settings.pages.faction.openOc", label: "Open ready OCs", group: "qol", section: "faction", keywords: ["organized crime"] },
	{
		path: "settings.pages.faction.availablePlayers",
		label: "Show amount of available players for OC",
		group: "qol",
		section: "faction",
		keywords: ["organized crime"],
	},
	{
		path: "settings.pages.faction.recommendedNnb",
		label: "Show recommended NNB per OC",
		group: "qol",
		section: "faction",
		keywords: ["organized crime"],
	},
	{ path: "settings.pages.faction.ocNnb", label: "Show a user's NNB", group: "qol", section: "faction", keywords: ["organized crime"] },
	{ path: "settings.pages.faction.ocTimes", label: "Show OC times on the faction page", group: "qol", section: "faction", keywords: ["organized crime"] },
	{ path: "settings.pages.faction.ocLastAction", label: "Show last action on OC details", group: "qol", section: "faction", keywords: ["organized crime"] },
	{
		path: "settings.pages.faction.warnCrime",
		label: "Warn when joining a crime without passing the conditions",
		group: "qol",
		section: "faction",
		keywords: ["organized crime"],
	},
	{ path: "settings.pages.faction.rankedWarValue", label: "Show the total rewards for ranked wars", group: "qol", section: "faction" },
	{ path: "settings.pages.faction.warReportHighlight", label: "Highlight yourself in war reports", group: "qol", section: "faction" },

	// Section: profile
	{ path: "settings.pages.profile.avgpersonalstats", label: "Calculate average personal stats", group: "qol", section: "profile" },
	{ path: "settings.pages.profile.idBesideProfileName", label: "Reformat profile page headings as USERNAME [ID]", group: "qol", section: "profile" },
	{ path: "settings.pages.profile.statusIndicator", label: "Show user's status indicator next to their name", group: "qol", section: "profile" },
	{ path: "settings.pages.profile.notes", label: "Show profile notes", group: "qol", section: "profile" },
	{ path: "settings.pages.profile.ageToWords", label: "Show age of profile in words", group: "qol", section: "profile" },
	{ path: "settings.pages.profile.box", label: "Show the profile box", group: "qol", section: "profile" },
	{ path: "settings.pages.profile.boxFetch", label: "Profile box: automatically fetch data from the API", group: "qol", section: "profile" },
	{ path: "settings.pages.profile.boxStats", label: "Profile box: display personal stats", group: "qol", section: "profile" },
	{ path: "settings.pages.profile.boxSpy", label: "Profile box: show known spy results", group: "qol", section: "profile" },
	{ path: "settings.pages.profile.boxStakeout", label: "Profile box: enable stakeout options", group: "qol", section: "profile" },
	{ path: "settings.pages.profile.boxAttackHistory", label: "Profile box: show your attack history", group: "qol", section: "profile" },

	// Section: companies
	{ path: "settings.pages.companies.idBesideCompanyName", label: "Reformat company names as COMPANYNAME [ID]", group: "qol", section: "companies" },
	{ path: "settings.pages.companies.specials", label: "Help with company specials", group: "qol", section: "companies" },
	{ path: "settings.pages.joblist.specials", label: "Show company specials on the job list", group: "qol", section: "companies" },
	{
		path: "settings.pages.companies.autoStockFill",
		label: "Automatically fill company stock based on previous day sales",
		group: "qol",
		section: "companies",
	},
	{ path: "settings.pages.companies.employeeEffectiveness", label: "Employee effectiveness warning", group: "qol", section: "companies" },

	// Section: gym
	{ path: "settings.pages.gym.specialist", label: "Show specialist gym requirements", group: "qol", section: "gym" },
	{ path: "settings.pages.gym.disableStats", label: "Allow stats to be disabled in gym", group: "qol", section: "gym" },
	{ path: "settings.pages.gym.steadfast", label: "Show current steadfast bonus for each stat", group: "qol", section: "gym" },
	{ path: "settings.pages.gym.progress", label: "Display estimated gym energy progress", group: "qol", section: "gym" },
	{ path: "settings.pages.gym.graph", label: "Display gym stat graph", group: "qol", section: "gym" },

	// Section: speed
	{ path: "settings.pages.crimes.quickCrimes", label: "Quick Crimes", group: "qol", section: "speed" },
	{ path: "settings.pages.trade.openChat", label: "Chat button in trades", group: "qol", section: "speed" },
	{ path: "settings.scripts.noConfirm.itemEquip", label: "No confirm: Equipping items", group: "qol", section: "speed" },
	{ path: "settings.scripts.noConfirm.tradeAccept", label: "No confirm: Accepting trades", group: "qol", section: "speed" },
	{ path: "settings.scripts.noConfirm.pointsMarketBuy", label: "No confirm: Buying points from the market", group: "qol", section: "speed" },
	{ path: "settings.scripts.noConfirm.pointsMarketRemove", label: "No confirm: Removing points from the market", group: "qol", section: "speed" },
	{ path: "settings.scripts.noConfirm.abroadItemBuy", label: "No confirm: Buying items aboard", group: "qol", section: "speed" },
	{ path: "settings.scripts.noConfirm.propertiesSell", label: "No confirm: Selling your properties", group: "qol", section: "speed", keywords: ["property"] },

	/*
	 * Connections
	 */
	// Section: services
	{ path: "settings.external.tornstats", label: "Enable TornStats", group: "connections", section: "services" },
	{ path: "api.tornstats.key", label: "TornStats API key", group: "connections", section: "services" },
	{ path: "settings.external.yata", label: "Enable YATA", group: "connections", section: "services" },
	{ path: "api.yata.key", label: "YATA API key", group: "connections", section: "services" },
	{ path: "settings.external.prometheus", label: "Enable Prometheus", group: "connections", section: "services" },
	{ path: "settings.external.lzpt", label: "Enable LZPT", group: "connections", section: "services" },
	{ path: "settings.external.tornw3b", label: "Enable TornW3B", group: "connections", section: "services" },
	{ path: "settings.external.ffScouter", label: "Enable FFScouter", group: "connections", section: "services", keywords: ["ff scouter", "ff-scouter"] },
	{ path: "api.ffScouter.key", label: "FFScouter API key", group: "connections", section: "services" },
	{ path: "settings.external.tornintel", label: "Enable Torn Intel", group: "connections", section: "services" },
];
