const TEAM = [
	{
		name: "Mephiles",
		title: ["Creator", "Developer"],
		core: true,
		torn: 2087524,
		color: "green",
		donations: [
			{
				name: "PayPal",
				link: "https://paypal.me/gkaljulaid",
			},
		],
	},
	{
		name: "DeKleineKobini",
		title: "Maintainer / Developer",
		core: true,
		torn: 2114440,
		color: "orange",
		donations: [
			{
				name: "PayPal",
				link: "https://paypal.me/kkobini",
			},
			{
				name: "Buy Me a Coffee",
				link: "https://www.buymeacoffee.com/dekleinekobini",
			},
		],
	},
	{
		name: "TheFoxMan",
		title: "Developer",
		core: true,
		torn: 1936821,
		color: "greenyellow",
	},
	{
		name: "Allo",
		title: "Community Admin",
		core: true,
		torn: 2316070,
		color: "royalblue",
	},
	{
		name: "AllMight",
		title: "Developer",
		core: false,
		torn: 1878147,
		color: "#ff3333",
	},
	{
		name: "wootty2000",
		title: "Developer",
		core: false,
		torn: 2344687,
		color: "red",
	},
	{
		name: "finally",
		title: "Developer",
		core: false,
		torn: 2060206,
		color: "purple",
	},
	{
		name: "Fogest",
		title: "Developer",
		core: false,
		torn: 2254826,
		color: "chartreuse",
	},
	{
		name: "smikula",
		title: "Developer",
		core: false,
		// torn:
		color: "#fbff09",
	},
	{
		name: "kontamusse",
		title: "Developer",
		core: false,
		torn: 2408039,
		color: "#58e4e4",
	},
	{
		name: "Natty_Boh",
		title: "Developer",
		core: false,
		torn: 1651049,
		color: "blue",
	},
	{
		name: "h4xnoodle",
		title: "Developer",
		core: false,
		torn: 2315090,
		color: "teal",
	},
	{
		name: "Tesa",
		title: "Developer",
		core: false,
		torn: 2639608,
		color: "brown",
	},
	{
		name: "hvr-lust",
		title: "Developer",
		core: false,
		color: "darkkhaki",
	},
	{
		name: "ORAN",
		title: "Developer",
		core: false,
		torn: 1778676,
		color: "mediumpurple",
	},
	{
		name: "dat-mule",
		title: "Developer",
		core: false,
		torn: 2043166,
		color: "cornflowerblue",
	},
	{
		name: "josephting",
		title: "Developer",
		core: false,
		torn: 2272298,
		color: "maroon",
	},
	{
		name: "Lazerpent",
		title: "Developer",
		core: false,
		torn: 2112641,
		color: "#7E46DA",
	},
	{
		name: "No1IrishStig",
		title: "Developer",
		core: false,
		torn: 2648238,
		color: "#a6282c",
	},
	{
		name: "Acarya",
		title: "Developer",
		core: false,
		torn: 2243227,
		color: "springgreen",
	},
	{
		name: "Kwack",
		title: "Developer",
		core: false,
		torn: 2190604,
		color: "deeppink",
	},
	{
		name: "Conrado",
		title: "Developer",
		core: false,
		torn: 2631918,
		color: "cyan",
	},
	{
		name: "Vrasp",
		title: "Developer",
		core: false,
		torn: 2627614,
		color: "#01b0aa",
	},
	{
		name: "Anti0815",
		title: "Developer",
		core: false,
		torn: 2793691,
		color: "#0081fe",
	},
	{
		name: "LePluB",
		title: "Developer",
		core: false,
		torn: 2890448,
		color: "orange",
	},
	{
		name: "ThtAstronautGuy",
		title: "Developer",
		core: false,
		torn: 1977683,
		color: "#841210",
	},
	{
		name: "zachwozn",
		title: "Developer",
		core: false,
		torn: 2301700,
		color: "#017BC7",
	},
	{
		name: "nao",
		title: "Developer",
		core: false,
		torn: 2669774,
		color: "#9B1C31",
	},
	{
		name: "tiksan",
		title: "Developer",
		core: false,
		torn: 2383326,
		color: "white", // No explicit color chosen.
	},
	{
		name: "TravisTheTechie",
		title: "Developer",
		core: false,
		torn: 3549588,
		color: "firebrick",
	},
  {
    name: "MOBermejo",
		title: "Developer",
		core: false,
		torn: 3385879,
		color: "#DAA520",
  }
];

const CONTRIBUTORS = TEAM.filter(({ title, color }) => title.includes("Developer") || color).reduce(
	(object, { name, torn, color }) => ({ ...object, [name]: { id: torn, name, color } }),
	{}
);
