const RESPONSE__SEARCH_FOR_CASH_1: TornInternalAttemptCrime = {
	DB: {
		currentTemplate: "searchForCash",
		avoidStatsAndNerve: false,
		special: 0,
		additionalInfo: {
			barValue: 95,
			scale: 99,
			title: "Trash Collection: Mondays 06:00 - 18:00",
			progressIconState: 2,
			crimesListNeeded: true,
		},
		ID: 828,
		timestamp: 1771190997,
		specialRewardToOverride: [],
		demMod: 0,
		crimesByType: [
			{
				currentTemplate: "searchForCash",
				title: "Search the Trash",
				nerve: 2,
				iconClass: "search-cash-image-search-trash",
				crimeID: 1,
				subID: null,
				sortID: 1,
				requirements: {},
				available: true,
				locked: false,
				additionalInfo: {
					barValue: 95,
					scale: 99,
					title: "Trash Collection: Mondays 06:00 - 18:00",
					progressIconState: 2,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
				outcomeDesc: "",
				special: 0,
				rewardsGive: {
					userRewards: {
						money: 62,
					},
					itemsRewards: null,
					itemsLoseRewards: null,
					money: 62,
				},
				ID: 828,
				story: [
					"With the greatest respect, you search through the trash around the back of the church.",
					"There's a grocery bag full of smashed glass and scented oils inside the main dumpster.",
					"Pulling it out, you spot a small collection of oil-soaked cash beneath the bottles.",
					"You pick out the glass shards and pocket the aggressively fragrant dollars.",
				],
				timestamp: 1771190997,
				specialReward: [],
				specialRewardToOverride: [],
			},
			{
				currentTemplate: "searchForCash",
				title: "Search the Subway",
				nerve: 2,
				iconClass: "search-cash-image-search-train-station",
				crimeID: 2,
				subID: null,
				sortID: 2,
				requirements: {},
				available: true,
				locked: false,
				additionalInfo: {
					barValue: 79,
					scale: 79,
					title: "Status: Rush hour",
					progressIconState: 4,
					crimesListNeeded: true,
					dirtyBomb: false,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "searchForCash",
				title: "Search the Junkyard",
				nerve: 2,
				iconClass: "search-cash-image-search-scrap-yard",
				crimeID: 3,
				subID: null,
				sortID: 3,
				requirements: {},
				available: true,
				locked: false,
				additionalInfo: {
					barValue: 84,
					scale: 99,
					title: "Crushing: Weekdays 09:00 - 16:00",
					progressIconState: 1,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "searchForCash",
				title: "Search the Beach",
				nerve: 2,
				iconClass: "search-cash-image-search-beach",
				crimeID: 4,
				subID: null,
				sortID: 4,
				requirements: {
					items: [
						{
							label: "Metal Detector",
							value: 852,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
					],
				},
				available: false,
				locked: false,
				additionalInfo: {
					barValue: 41,
					scale: 41,
					title: "Tide: Mid-tide",
					progressIconState: 2,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "searchForCash",
				title: "Search the Cemetery",
				nerve: 2,
				iconClass: "search-cash-image-search-graveyard",
				crimeID: 5,
				subID: null,
				sortID: 5,
				requirements: {
					items: [
						{
							label: "Cemetery Key",
							value: 853,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
					],
				},
				available: false,
				locked: false,
				additionalInfo: {
					barValue: 75,
					scale: 99,
					title: "Groundskeeping: Weekdays 09:00 - 17:00",
					progressIconState: 1,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "searchForCash",
				title: "Search the Fountain",
				nerve: 2,
				iconClass: "search-cash-image-search-fountain",
				crimeID: 6,
				subID: null,
				sortID: 6,
				requirements: {
					minCrimeLevel: {
						value: 75,
						available: true,
					},
				},
				available: true,
				locked: false,
				additionalInfo: {
					barValue: 46,
					scale: 48,
					title: "Collections: 1st of the month 13:00 - 16:00",
					progressIconState: 1,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
		],
		skillLevelTotal: 0,
		currentLevel: 100,
		lastSubCrimeID: 1,
		lastSubCrimeIDByType: 1,
		currentUserStats: {
			attemptsTotal: 4592,
			crimesByIDAttempts: {
				"2": 1036,
				"3": 872,
				"1": 649,
				"4": 916,
				"5": 806,
				"6": 313,
			},
			crimesByIDAttemptsSucc: {
				"2": 978,
				"3": 731,
				"1": 554,
				"4": 702,
				"5": 619,
				"6": 289,
			},
			moneyFoundTotal: 460678,
			nerveUsed: 9184,
			successesTotal: 3873,
			itemsFound: {
				"41": 40,
				"1123": 93,
				"417": 21,
				"956": 15,
				"1239": 5,
				"1219": 12,
				"885": 331,
				"372": 38,
				"897": 1075,
				"909": 77,
				"44": 14,
				"527": 8,
				"8": 3,
				"980": 4,
				"1269": 16,
				"403": 73,
				"1205": 10,
				"884": 115,
				"3": 9,
				"1254": 37,
				"432": 12,
				"887": 22,
				"37": 17,
				"889": 22,
				"875": 4,
				"878": 8,
				"883": 7,
				"877": 5,
				"650": 20,
				"66": 10,
				"856": 11,
				"857": 9,
				"862": 14,
				"852": 1,
				"196": 32,
				"1208": 12,
				"1214": 33,
				"1087": 12,
				"1235": 2,
				"180": 145,
				"412": 5,
				"414": 5,
				"890": 25,
				"60": 15,
				"623": 14,
				"1081": 22,
				"895": 20,
				"1082": 34,
				"886": 18,
				"564": 1,
				"880": 7,
				"882": 10,
				"876": 4,
				"881": 5,
				"896": 12,
				"898": 15,
				"42": 46,
				"62": 7,
				"172": 11,
				"868": 11,
				"860": 10,
				"859": 12,
				"640": 1,
				"853": 1,
				"1080": 40,
				"154": 1,
				"904": 55,
				"1078": 23,
				"197": 5,
				"199": 2,
				"205": 12,
				"206": 1,
				"401": 15,
				"1096": 23,
				"43": 3,
				"1201": 12,
				"858": 12,
				"1231": 3,
				"265": 5,
				"430": 1,
				"935": 1,
				"1089": 19,
				"907": 108,
				"1093": 8,
				"489": 8,
				"902": 70,
				"621": 1,
				"622": 1,
				"625": 1,
				"626": 1,
				"1226": 13,
				"888": 30,
				"905": 22,
				"183": 32,
				"1092": 9,
				"901": 94,
				"53": 30,
				"54": 19,
				"55": 33,
				"906": 7,
				"1232": 28,
				"892": 18,
				"129": 34,
				"1": 11,
				"184": 11,
				"48": 18,
				"1234": 9,
				"1079": 6,
				"1085": 4,
				"894": 4,
				"879": 2,
				"104": 8,
				"204": 8,
				"1210": 5,
				"64": 2,
				"903": 31,
				"900": 1,
				"181": 6,
				"1084": 4,
				"1292": 11,
				"97": 8,
				"861": 2,
				"1094": 12,
				"893": 1,
				"1125": 26,
				"941": 4,
				"1268": 6,
				"407": 5,
				"1083": 7,
				"641": 1,
				"65": 2,
				"1233": 5,
				"1253": 3,
				"4": 2,
				"408": 1,
				"1211": 1,
				"616": 1,
				"227": 4,
				"56": 3,
				"863": 3,
				"201": 1,
				"61": 2,
				"1199": 1,
				"899": 1,
				"566": 1,
				"270": 2,
				"603": 1,
				"67": 2,
				"565": 1,
				"833": 1,
			},
			failedTotal: 689,
			critFailedTotal: 30,
			jailedTotal: 28,
			ammoFoundTotal: 700,
			statsByType: {
				"1": {
					successesTotal: 0,
				},
			},
			skill: 100,
			skillLevel: 0,
			enhancer: {
				name: "Glasses",
				available: true,
			},
		},
		currentUserStatistics: [
			{
				label: "Skill",
				value: "100.00",
			},
			{
				label: "Crime type",
				value: "Theft",
			},
			{
				label: "Progression bonus",
				value: "40%",
			},
			{
				label: "Enhancer",
				value: "Glasses",
				available: true,
			},
			{
				label: "Total attempts",
				value: "4,592",
			},
			{
				label: "Successes",
				value: "3,873",
			},
			{
				label: "Fails",
				value: "689",
			},
			{
				label: "Critical fails",
				value: "30",
			},
			{
				label: "Unique outcomes",
				value: "34 \/ 34",
			},
			{
				label: "Rotten items discovered",
				value: "7 \/ 7",
			},
			{
				label: "Trash searched",
				value: "554 \/ 649",
			},
			{
				label: "Subway searched",
				value: "978 \/ 1036",
			},
			{
				label: "Junkyard searched",
				value: "731 \/ 872",
			},
			{
				label: "Beach searched",
				value: "702 \/ 916",
			},
			{
				label: "Cemetery searched",
				value: "619 \/ 806",
			},
			{
				label: "Fountain searched",
				value: "289 \/ 313",
			},
			{
				label: "Money found",
				value: "$460,678",
			},
			{
				label: "Ammo found",
				value: "700",
			},
			{
				label: "Total items found",
				value: "3,756",
			},
			{
				label: "Axe",
				value: "3",
			},
			{
				label: "Bag of Bon Bons",
				value: "17",
			},
			{
				label: "Bag of Candy Kisses",
				value: "8",
			},
			{
				label: "Bank Statement",
				value: "7",
			},
			{
				label: "Beach Ball",
				value: "12",
			},
			{
				label: "Billfold",
				value: "40",
			},
			{
				label: "Blank DVDs",
				value: "15",
			},
			{
				label: "Blank DVDs : 100",
				value: "14",
			},
			{
				label: "Blanket",
				value: "2",
			},
			{
				label: "Bone",
				value: "11",
			},
			{
				label: "Bottle Cap",
				value: "1,075",
			},
			{
				label: "Bottle of Beer",
				value: "145",
			},
			{
				label: "Bottle of Champagne",
				value: "6",
			},
			{
				label: "Box of Tissues",
				value: "73",
			},
			{
				label: "Bunch of Black Roses",
				value: "11",
			},
			{
				label: "Bunch of Carnations",
				value: "70",
			},
			{
				label: "Bunch of Flowers",
				value: "8",
			},
			{
				label: "CD Player",
				value: "3",
			},
			{
				label: "Candle",
				value: "108",
			},
			{
				label: "Cannabis",
				value: "32",
			},
			{
				label: "Car Battery",
				value: "115",
			},
			{
				label: "Car Keys",
				value: "22",
			},
			{
				label: "Card Skimmer",
				value: "26",
			},
			{
				label: "Cardholder",
				value: "6",
			},
			{
				label: "Casket",
				value: "1",
			},
			{
				label: "Cell Phone",
				value: "23",
			},
			{
				label: "Cemetery Key",
				value: "1",
			},
			{
				label: "Clutch",
				value: "7",
			},
			{
				label: "Coconut Bra",
				value: "1",
			},
			{
				label: "Coin Purse",
				value: "22",
			},
			{
				label: "Compass",
				value: "5",
			},
			{
				label: "Cork Hat",
				value: "1",
			},
			{
				label: "Cosmetics Case",
				value: "4",
			},
			{
				label: "Cough Syrup",
				value: "16",
			},
			{
				label: "Crazy Straw",
				value: "12",
			},
			{
				label: "Credit Card",
				value: "4",
			},
			{
				label: "Crowbar",
				value: "9",
			},
			{
				label: "DVD Player",
				value: "40",
			},
			{
				label: "Daffodil",
				value: "94",
			},
			{
				label: "Diamond Ring",
				value: "19",
			},
			{
				label: "Diving Gloves",
				value: "1",
			},
			{
				label: "Dozen Roses",
				value: "34",
			},
			{
				label: "Ecstasy",
				value: "5",
			},
			{
				label: "Empty Box",
				value: "38",
			},
			{
				label: "Family Photo",
				value: "19",
			},
			{
				label: "Fertilizer",
				value: "13",
			},
			{
				label: "Festering Chicken",
				value: "4",
			},
			{
				label: "First Aid Kit",
				value: "2",
			},
			{
				label: "Fishing Rod",
				value: "1",
			},
			{
				label: "Flippers",
				value: "1",
			},
			{
				label: "Funeral Wreath",
				value: "55",
			},
			{
				label: "Game Console",
				value: "8",
			},
			{
				label: "Garden Gnome",
				value: "28",
			},
			{
				label: "Gasoline",
				value: "11",
			},
			{
				label: "Glasses",
				value: "1",
			},
			{
				label: "Gold Ring",
				value: "30",
			},
			{
				label: "Gold Watch",
				value: "15",
			},
			{
				label: "Golden Wreath",
				value: "1",
			},
			{
				label: "Golf Club",
				value: "3",
			},
			{
				label: "Hammer",
				value: "11",
			},
			{
				label: "Handkerchief",
				value: "7",
			},
			{
				label: "Headphones",
				value: "25",
			},
			{
				label: "High-Speed Drive",
				value: "1",
			},
			{
				label: "Hit Contract",
				value: "8",
			},
			{
				label: "Hoe",
				value: "5",
			},
			{
				label: "Insurance Policy",
				value: "10",
			},
			{
				label: "Jacket",
				value: "18",
			},
			{
				label: "Kevlar Gloves",
				value: "1",
			},
			{
				label: "Knuckle Dusters",
				value: "2",
			},
			{
				label: "LSD",
				value: "2",
			},
			{
				label: "Ladder",
				value: "4",
			},
			{
				label: "Laptop",
				value: "1",
			},
			{
				label: "Lead Pipe",
				value: "15",
			},
			{
				label: "Leather Gloves",
				value: "20",
			},
			{
				label: "Lipstick",
				value: "4",
			},
			{
				label: "Lost and Found Office Key",
				value: "1",
			},
			{
				label: "Lubricant",
				value: "9",
			},
			{
				label: "Lucky Quarter",
				value: "1",
			},
			{
				label: "Luger",
				value: "8",
			},
			{
				label: "MP3 Player",
				value: "46",
			},
			{
				label: "Magazine",
				value: "22",
			},
			{
				label: "Metal Detector",
				value: "1",
			},
			{
				label: "Microwave",
				value: "7",
			},
			{
				label: "Mix CD",
				value: "18",
			},
			{
				label: "Moldy Pizza",
				value: "5",
			},
			{
				label: "Morphine",
				value: "10",
			},
			{
				label: "Mountain Bike",
				value: "1",
			},
			{
				label: "Old Wallet",
				value: "23",
			},
			{
				label: "Oxygen Tank",
				value: "12",
			},
			{
				label: "PCP",
				value: "1",
			},
			{
				label: "Pack of Cuban Cigars",
				value: "2",
			},
			{
				label: "Pantyhose",
				value: "4",
			},
			{
				label: "Pearl Necklace",
				value: "33",
			},
			{
				label: "Pele Charm",
				value: "5",
			},
			{
				label: "Personal Computer",
				value: "2",
			},
			{
				label: "Phone Card",
				value: "20",
			},
			{
				label: "Proda Sunglasses",
				value: "5",
			},
			{
				label: "RS232 Cable",
				value: "21",
			},
			{
				label: "Rope",
				value: "12",
			},
			{
				label: "Rotten Apple",
				value: "4",
			},
			{
				label: "Sand",
				value: "1",
			},
			{
				label: "Scrap Metal",
				value: "331",
			},
			{
				label: "Sextant",
				value: "1",
			},
			{
				label: "Shovel",
				value: "9",
			},
			{
				label: "Silver Bead",
				value: "1",
			},
			{
				label: "Silver Coin",
				value: "15",
			},
			{
				label: "Silver Necklace",
				value: "3",
			},
			{
				label: "Single Red Rose",
				value: "32",
			},
			{
				label: "Smelly Cheese",
				value: "8",
			},
			{
				label: "Snorkel",
				value: "1",
			},
			{
				label: "Soccer Ball",
				value: "2",
			},
			{
				label: "Sour Milk",
				value: "2",
			},
			{
				label: "Spear",
				value: "4",
			},
			{
				label: "Speed",
				value: "8",
			},
			{
				label: "Speedo",
				value: "14",
			},
			{
				label: "Spoiled Fish",
				value: "5",
			},
			{
				label: "Sports Shades",
				value: "5",
			},
			{
				label: "Spray Paint : Black",
				value: "11",
			},
			{
				label: "Spray Paint : Blue",
				value: "10",
			},
			{
				label: "Spray Paint : Green",
				value: "2",
			},
			{
				label: "Spray Paint : Orange",
				value: "3",
			},
			{
				label: "Spray Paint : Pink",
				value: "12",
			},
			{
				label: "Spray Paint : Purple",
				value: "12",
			},
			{
				label: "Spray Paint : Red",
				value: "9",
			},
			{
				label: "Spray Paint : White",
				value: "14",
			},
			{
				label: "Spy Camera",
				value: "93",
			},
			{
				label: "Stale Bread",
				value: "7",
			},
			{
				label: "Stash Box",
				value: "5",
			},
			{
				label: "Subway Pass",
				value: "12",
			},
			{
				label: "Syringe",
				value: "12",
			},
			{
				label: "Tampon",
				value: "12",
			},
			{
				label: "Television",
				value: "2",
			},
			{
				label: "Tin Can",
				value: "77",
			},
			{
				label: "Tire",
				value: "37",
			},
			{
				label: "Torn City Times",
				value: "18",
			},
			{
				label: "Towel",
				value: "33",
			},
			{
				label: "Tractor Part",
				value: "3",
			},
			{
				label: "Travel Mug",
				value: "22",
			},
			{
				label: "Trout",
				value: "1",
			},
			{
				label: "Turkey Baster",
				value: "11",
			},
			{
				label: "Umbrella",
				value: "30",
			},
			{
				label: "Vicodin",
				value: "12",
			},
			{
				label: "Vitamins",
				value: "6",
			},
			{
				label: "WWII Helmet",
				value: "1",
			},
			{
				label: "Wetsuit",
				value: "1",
			},
			{
				label: "Wheelbarrow",
				value: "5",
			},
			{
				label: "White Lily",
				value: "31",
			},
			{
				label: "Wrench",
				value: "10",
			},
			{
				label: "Xanax",
				value: "1",
			},
			{
				label: "Zip Wallet",
				value: "34",
			},
		],
		tutorial: null,
		outcome: {
			ID: 828,
			result: "success",
			special: false,
			story: [
				"With the greatest respect, you search through the trash around the back of the church.",
				"There's a grocery bag full of smashed glass and scented oils inside the main dumpster.",
				"Pulling it out, you spot a small collection of oil-soaked cash beneath the bottles.",
				"You pick out the glass shards and pocket the aggressively fragrant dollars.",
			],
			rewards: [
				{
					type: "money",
					value: 62,
				},
			],
		},
		user: {
			playername: "DeKleineKobini",
			nerve: 9,
			money: 26421258,
			isAdmin: false,
			isUnderAttack: false,
		},
		time: 1771190997,
	},
};

const RESPONSE__BOOTLEGGING_1: TornInternalAttemptCrime = {
	DB: {
		currentTemplate: "BootleggingMakeCD",
		avoidStatsAndNerve: false,
		special: 0,
		additionalInfo: {
			timeLeftForNextCD: 10,
			currentQueue: [
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
				"5",
			],
			CDsAmount: 0,
			timeForCD: 10,
			blankCDs: 221,
			crimesListNeeded: true,
		},
		ID: 11772,
		timestamp: 1771191380,
		specialRewardToOverride: [],
		demMod: 0,
		crimesByType: [
			{
				currentTemplate: "BootleggingMakeCD",
				title: "Copy DVDs",
				nerve: 2,
				iconClass: "bootlegging-image-copy-some-cds",
				crimeID: 8,
				subID: null,
				sortID: 1,
				requirements: {
					items: [
						{
							label: "Personal Computer",
							value: 61,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
						{
							label: "Laptop",
							value: 154,
							count: 26,
							requiredAmount: 1,
							consume: false,
							available: true,
						},
						{
							label: "Gold Laptop",
							value: 381,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
						{
							label: "Blank DVDs : 100",
							value: 44,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
							blankCDsCount: 100,
						},
						{
							label: "Blank DVDs : 250",
							value: 956,
							count: 3,
							requiredAmount: 1,
							consume: false,
							available: true,
							blankCDsCount: 250,
						},
						{
							label: "Blank DVDs : 50",
							value: 957,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
							blankCDsCount: 50,
						},
					],
				},
				available: true,
				locked: false,
				additionalInfo: {
					timeForCD: 10,
					timeLeftForNextCD: 10,
					currentQueue: [
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
						"5",
					],
					blankCDs: 221,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
				outcomeDesc: "29 blank DVDs lost",
				special: 0,
				rewardsGive: {
					itemsRewards: null,
					itemsLoseRewards: null,
				},
				ID: 11772,
				story: [
					"Checking the TV listings, you see a major network has a horror movie marathon planned for next Saturday.",
					"Nobody likes to wait for things these days, so you decide to capitalize on this forthcoming event.",
					"Rifling through your DVD collection, you pull out as many horror movies as you can find.",
					"With a decent stack by your side, you start copying them one by one.",
				],
				timestamp: 1771191380,
				specialReward: {
					type: "other",
					value: "29 blank DVDs lost",
				},
				specialRewardToOverride: [],
			},
			{
				currentTemplate: "BootleggingSellCD",
				title: "Sell Counterfeit DVDs",
				nerve: 5,
				iconClass: "bootlegging-image-sell-counterfeit-cds",
				crimeID: 9,
				subID: null,
				sortID: 2,
				requirements: {},
				available: true,
				locked: false,
				additionalInfo: {
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "BootleggingCollectFunds",
				title: "Online Store",
				nerve: 1,
				iconClass: "bootlegging-image-setup-collect-funds",
				crimeID: 11,
				subID: null,
				sortID: 4,
				requirements: {
					items: [
						{
							label: "Personal Computer",
							value: 61,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
						{
							label: "Laptop",
							value: 154,
							count: 26,
							requiredAmount: 1,
							consume: false,
							available: true,
						},
						{
							label: "Gold Laptop",
							value: 381,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
					],
					minCrimeLevel: {
						value: 50,
						available: true,
					},
				},
				available: true,
				locked: false,
				additionalInfo: {
					lastMoneyCheckStamp: 1771191380,
					CDs: {
						"1": 0,
						"2": 0,
						"3": 0,
						"4": 0,
						"7": 0,
						"5": 0,
						"6": 0,
						"8": 0,
					},
					moneyToCollect: 0,
					enabled: true,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
		],
		generalInfo: {
			CDsDiff: {},
			moneyDiff: 0,
			CDs: {
				"1": 0,
				"2": 0,
				"3": 0,
				"4": 0,
				"7": 0,
				"5": 0,
				"6": 0,
				"8": 0,
			},
			lastCDType: "Horror",
		},
		skillLevelTotal: 0,
		currentLevel: 100,
		lastSubCrimeID: 8,
		lastSubCrimeIDByType: 8,
		currentUserStats: {
			attemptsTotal: 5628,
			crimesByIDAttempts: {
				"8": 4726,
				"9": 317,
				"10": 26,
				"11": 559,
			},
			crimesByIDAttemptsSucc: {
				"8": 4701,
				"9": 303,
				"10": 23,
				"11": 559,
			},
			moneyFoundTotal: 2320646,
			nerveUsed: 11856,
			successesTotal: 5586,
			critFailedTotal: 7,
			CDsCopiedTotal: 99620,
			failedTotal: 35,
			CDType1Sold: 21984,
			CDType2Sold: 16279,
			CDType3Sold: 10024,
			CDType4Sold: 11126,
			CDsSoldTotal: 99620,
			moneyMadeTotal: 2323306,
			sellMoney: 929586,
			CDType7Sold: 10004,
			CDType8Sold: 10024,
			CDType5Sold: 10151,
			CDType6Sold: 10028,
			jailedTotal: 2,
			onlineStoreCustomers: 34478.220150000096,
			onlineStoreVisits: 3085463,
			onlineMoney: 1393740,
			salesTotal: 69687,
			collectSucc: 559,
			collectTotal: 559,
			moneyMadeOnlineStore: 1393720,
			specialAmmoFoundTotal: 500,
			itemsFound: {
				"369": 1,
				"819": 1,
				"366": 1,
			},
			statsByType: {
				"2": {
					successesTotal: 0,
				},
			},
			skill: 100,
			skillLevel: 0,
			enhancer: {
				name: "High-Speed Drive",
				available: true,
			},
		},
		currentUserStatistics: [
			{
				label: "Skill",
				value: "100.00",
			},
			{
				label: "Crime type",
				value: "Counterfeiting",
			},
			{
				label: "Progression bonus",
				value: "40%",
			},
			{
				label: "Enhancer",
				value: "High-Speed Drive",
				available: true,
			},
			{
				label: "Total attempts",
				value: "5,628",
			},
			{
				label: "Successes",
				value: "5,586",
			},
			{
				label: "Fails",
				value: "35",
			},
			{
				label: "Critical fails",
				value: "7",
			},
			{
				label: "Unique outcomes",
				value: "4 \/ 4",
			},
			{
				label: "Total DVDs copied",
				value: "99,620",
			},
			{
				label: "Money made",
				value: "$2,323,306",
			},
			{
				label: "Sell DVDs earnings",
				value: "$929,586",
			},
			{
				label: "Online store earnings",
				value: "$1,393,720",
			},
			{
				label: "Copy DVDs attempts",
				value: "4701 \/ 4726",
			},
			{
				label: "Sell DVDs attempts",
				value: "303 \/ 317",
			},
			{
				label: "Store setup attempts",
				value: "23 \/ 26",
			},
			{
				label: "Collect attempts",
				value: "559 \/ 559",
			},
			{
				label: "Online store visits",
				value: "3,085,463",
			},
			{
				label: "Online store customers",
				value: "34,479",
			},
			{
				label: "Online store sales",
				value: "69,687",
			},
			{
				label: "Total DVDs sold",
				value: "99,620",
			},
			{
				label: "Action DVDs sold",
				value: "21,984",
			},
			{
				label: "Comedy DVDs sold",
				value: "16,279",
			},
			{
				label: "Drama DVDs sold",
				value: "10,024",
			},
			{
				label: "Fantasy DVDs sold",
				value: "11,126",
			},
			{
				label: "Horror DVDs sold",
				value: "10,151",
			},
			{
				label: "Romance DVDs sold",
				value: "10,028",
			},
			{
				label: "Thriller DVDs sold",
				value: "10,004",
			},
			{
				label: "Sci-Fi DVDs sold",
				value: "10,024",
			},
		],
		tutorial: null,
		outcome: {
			ID: 11772,
			result: "success",
			special: false,
			story: [
				"Checking the TV listings, you see a major network has a horror movie marathon planned for next Saturday.",
				"Nobody likes to wait for things these days, so you decide to capitalize on this forthcoming event.",
				"Rifling through your DVD collection, you pull out as many horror movies as you can find.",
				"With a decent stack by your side, you start copying them one by one.",
			],
			rewards: [
				{
					type: "other",
					text: "Copying 29 Horror DVDs",
				},
			],
		},
		user: {
			playername: "DeKleineKobini",
			nerve: 9,
			money: 26421258,
			isAdmin: false,
			isUnderAttack: false,
		},
		time: 1771191380,
	},
};

const RESPONSE__BOOTLEGGING_2: TornInternalAttemptCrime = {
	DB: {
		currentTemplate: "BootleggingSellCD",
		avoidStatsAndNerve: false,
		special: 0,
		additionalInfo: {
			CDs: {
				"1": 0,
				"2": 0,
				"3": 0,
				"4": 0,
				"7": 0,
				"5": 0,
				"6": 0,
				"8": 0,
			},
			customers: 1,
			sold: 1,
			crimesListNeeded: true,
		},
		ID: 1367,
		timestamp: 1771191425,
		specialRewardToOverride: [],
		demMod: 0,
		crimesByType: [
			{
				currentTemplate: "BootleggingMakeCD",
				title: "Copy DVDs",
				nerve: 2,
				iconClass: "bootlegging-image-copy-some-cds",
				crimeID: 8,
				subID: null,
				sortID: 1,
				requirements: {
					items: [
						{
							label: "Personal Computer",
							value: 61,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
						{
							label: "Laptop",
							value: 154,
							count: 26,
							requiredAmount: 1,
							consume: false,
							available: true,
						},
						{
							label: "Gold Laptop",
							value: 381,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
						{
							label: "Blank DVDs : 100",
							value: 44,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
							blankCDsCount: 100,
						},
						{
							label: "Blank DVDs : 250",
							value: 956,
							count: 3,
							requiredAmount: 1,
							consume: false,
							available: true,
							blankCDsCount: 250,
						},
						{
							label: "Blank DVDs : 50",
							value: 957,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
							blankCDsCount: 50,
						},
					],
				},
				available: true,
				locked: false,
				additionalInfo: {
					timeForCD: 10,
					timeLeftForNextCD: 5,
					currentQueue: ["5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5"],
					blankCDs: 221,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "BootleggingSellCD",
				title: "Sell Counterfeit DVDs",
				nerve: 5,
				iconClass: "bootlegging-image-sell-counterfeit-cds",
				crimeID: 9,
				subID: null,
				sortID: 2,
				enoughNerve: 5,
				requirements: {},
				available: false,
				locked: false,
				additionalInfo: {
					CDs: {
						"1": 0,
						"2": 0,
						"3": 0,
						"4": 0,
						"7": 0,
						"5": 0,
						"6": 0,
						"8": 0,
					},
					customers: 1,
					sold: 1,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
				outcomeDesc: "3 DVDs lost",
				special: 0,
				rewardsGive: {
					userRewards: {
						money: 93,
					},
					itemsRewards: null,
					itemsLoseRewards: null,
					money: 93,
				},
				ID: 1367,
				story: [
					"You take the subway to the airport and set your DVDs out on a bench in the departure lounge.",
					"A horde of bored travelers crowds around your stall.",
					'"Their in-flight movies suck," announces one woman.',
					"\"I've seen Schindler's List 4: Tokyo Drift like fifteen times in the past month. You're a lifesaver!\" she adds.",
					"Her enthusiasm draws more customers to your wares.",
					"You sell 3 DVDs to the airport visitors.",
				],
				timestamp: 1771191425,
				specialReward: {
					type: "other",
					value: "3 DVDs lost",
				},
				specialRewardToOverride: [],
			},
			{
				currentTemplate: "BootleggingCollectFunds",
				title: "Online Store",
				nerve: 1,
				iconClass: "bootlegging-image-setup-collect-funds",
				crimeID: 11,
				subID: null,
				sortID: 4,
				requirements: {
					items: [
						{
							label: "Personal Computer",
							value: 61,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
						{
							label: "Laptop",
							value: 154,
							count: 26,
							requiredAmount: 1,
							consume: false,
							available: true,
						},
						{
							label: "Gold Laptop",
							value: 381,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
					],
					minCrimeLevel: {
						value: 50,
						available: true,
					},
				},
				available: true,
				locked: false,
				additionalInfo: {
					lastMoneyCheckStamp: 1771191425,
					CDs: {
						"1": 0,
						"2": 0,
						"3": 0,
						"4": 0,
						"7": 0,
						"5": 0,
						"6": 0,
						"8": 0,
					},
					moneyToCollect: 20,
					enabled: true,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
		],
		generalInfo: {
			CDsDiff: {
				"5": -3,
			},
			moneyDiff: 0,
			CDs: {
				"1": 0,
				"2": 0,
				"3": 0,
				"4": 0,
				"7": 0,
				"5": 0,
				"6": 0,
				"8": 0,
			},
			lastCDType: "Horror",
		},
		skillLevelTotal: 0,
		currentLevel: 100,
		lastSubCrimeID: 9,
		lastSubCrimeIDByType: 9,
		currentUserStats: {
			attemptsTotal: 5629,
			crimesByIDAttempts: {
				"8": 4726,
				"9": 318,
				"10": 26,
				"11": 559,
			},
			crimesByIDAttemptsSucc: {
				"8": 4701,
				"9": 304,
				"10": 23,
				"11": 559,
			},
			moneyFoundTotal: 2320739,
			nerveUsed: 11861,
			successesTotal: 5587,
			critFailedTotal: 7,
			CDsCopiedTotal: 99624,
			failedTotal: 35,
			CDType1Sold: 21984,
			CDType2Sold: 16279,
			CDType3Sold: 10024,
			CDType4Sold: 11126,
			CDsSoldTotal: 99624,
			moneyMadeTotal: 2323399,
			sellMoney: 929679,
			CDType7Sold: 10004,
			CDType8Sold: 10024,
			CDType5Sold: 10155,
			CDType6Sold: 10028,
			jailedTotal: 2,
			onlineStoreCustomers: 34478.485710000095,
			onlineStoreVisits: 3085465,
			onlineMoney: 1393760,
			salesTotal: 69688,
			collectSucc: 559,
			collectTotal: 559,
			moneyMadeOnlineStore: 1393720,
			specialAmmoFoundTotal: 500,
			itemsFound: {
				"369": 1,
				"819": 1,
				"366": 1,
			},
			statsByType: {
				"2": {
					successesTotal: 0,
				},
			},
			skill: 100,
			skillLevel: 0,
			enhancer: {
				name: "High-Speed Drive",
				available: true,
			},
		},
		currentUserStatistics: [
			{
				label: "Skill",
				value: "100.00",
			},
			{
				label: "Crime type",
				value: "Counterfeiting",
			},
			{
				label: "Progression bonus",
				value: "40%",
			},
			{
				label: "Enhancer",
				value: "High-Speed Drive",
				available: true,
			},
			{
				label: "Total attempts",
				value: "5,629",
			},
			{
				label: "Successes",
				value: "5,587",
			},
			{
				label: "Fails",
				value: "35",
			},
			{
				label: "Critical fails",
				value: "7",
			},
			{
				label: "Unique outcomes",
				value: "4 \/ 4",
			},
			{
				label: "Total DVDs copied",
				value: "99,624",
			},
			{
				label: "Money made",
				value: "$2,323,399",
			},
			{
				label: "Sell DVDs earnings",
				value: "$929,679",
			},
			{
				label: "Online store earnings",
				value: "$1,393,720",
			},
			{
				label: "Copy DVDs attempts",
				value: "4701 \/ 4726",
			},
			{
				label: "Sell DVDs attempts",
				value: "304 \/ 318",
			},
			{
				label: "Store setup attempts",
				value: "23 \/ 26",
			},
			{
				label: "Collect attempts",
				value: "559 \/ 559",
			},
			{
				label: "Online store visits",
				value: "3,085,465",
			},
			{
				label: "Online store customers",
				value: "34,479",
			},
			{
				label: "Online store sales",
				value: "69,688",
			},
			{
				label: "Total DVDs sold",
				value: "99,624",
			},
			{
				label: "Action DVDs sold",
				value: "21,984",
			},
			{
				label: "Comedy DVDs sold",
				value: "16,279",
			},
			{
				label: "Drama DVDs sold",
				value: "10,024",
			},
			{
				label: "Fantasy DVDs sold",
				value: "11,126",
			},
			{
				label: "Horror DVDs sold",
				value: "10,155",
			},
			{
				label: "Romance DVDs sold",
				value: "10,028",
			},
			{
				label: "Thriller DVDs sold",
				value: "10,004",
			},
			{
				label: "Sci-Fi DVDs sold",
				value: "10,024",
			},
		],
		tutorial: null,
		outcome: {
			ID: 1367,
			result: "success",
			special: false,
			story: [
				"You take the subway to the airport and set your DVDs out on a bench in the departure lounge.",
				"A horde of bored travelers crowds around your stall.",
				'"Their in-flight movies suck," announces one woman.',
				"\"I've seen Schindler's List 4: Tokyo Drift like fifteen times in the past month. You're a lifesaver!\" she adds.",
				"Her enthusiasm draws more customers to your wares.",
				"You sell 3 DVDs to the airport visitors.",
			],
			rewards: [
				{
					type: "money",
					value: 93,
				},
			],
		},
		user: {
			playername: "DeKleineKobini",
			nerve: 4,
			money: 26421351,
			isAdmin: false,
			isUnderAttack: false,
		},
		time: 1771191425,
	},
};

const RESPONSE__BOOTLEGGING_3: TornInternalAttemptCrime = {
	DB: {
		currentTemplate: "BootleggingCollectFunds",
		avoidStatsAndNerve: false,
		special: 0,
		additionalInfo: {
			lastMoneyCheckStamp: 1771191504,
			CDs: {
				"1": 0,
				"2": 0,
				"3": 0,
				"4": 0,
				"7": 0,
				"5": 6,
				"6": 0,
				"8": 0,
			},
			moneyToCollect: 0,
			enabled: true,
			crimesListNeeded: true,
		},
		ID: 8978,
		timestamp: 1771191504,
		specialRewardToOverride: [],
		demMod: 0,
		crimesByType: [
			{
				currentTemplate: "BootleggingMakeCD",
				title: "Copy DVDs",
				nerve: 2,
				iconClass: "bootlegging-image-copy-some-cds",
				crimeID: 8,
				subID: null,
				sortID: 1,
				requirements: {
					items: [
						{
							label: "Personal Computer",
							value: 61,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
						{
							label: "Laptop",
							value: 154,
							count: 26,
							requiredAmount: 1,
							consume: false,
							available: true,
						},
						{
							label: "Gold Laptop",
							value: 381,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
						{
							label: "Blank DVDs : 100",
							value: 44,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
							blankCDsCount: 100,
						},
						{
							label: "Blank DVDs : 250",
							value: 956,
							count: 3,
							requiredAmount: 1,
							consume: false,
							available: true,
							blankCDsCount: 250,
						},
						{
							label: "Blank DVDs : 50",
							value: 957,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
							blankCDsCount: 50,
						},
					],
				},
				available: true,
				locked: false,
				additionalInfo: {
					timeForCD: 10,
					timeLeftForNextCD: 6,
					currentQueue: ["5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5", "5"],
					blankCDs: 221,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "BootleggingSellCD",
				title: "Sell Counterfeit DVDs",
				nerve: 5,
				iconClass: "bootlegging-image-sell-counterfeit-cds",
				crimeID: 9,
				subID: null,
				sortID: 2,
				enoughNerve: 5,
				requirements: {},
				available: false,
				locked: false,
				additionalInfo: {
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "BootleggingCollectFunds",
				title: "Online Store",
				nerve: 1,
				iconClass: "bootlegging-image-setup-collect-funds",
				crimeID: 11,
				subID: null,
				sortID: 4,
				requirements: {
					items: [
						{
							label: "Personal Computer",
							value: 61,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
						{
							label: "Laptop",
							value: 154,
							count: 26,
							requiredAmount: 1,
							consume: false,
							available: true,
						},
						{
							label: "Gold Laptop",
							value: 381,
							count: 0,
							requiredAmount: 1,
							consume: false,
							available: false,
						},
					],
					minCrimeLevel: {
						value: 50,
						available: true,
					},
				},
				available: true,
				locked: false,
				additionalInfo: {
					lastMoneyCheckStamp: 1771191504,
					CDs: {
						"1": 0,
						"2": 0,
						"3": 0,
						"4": 0,
						"7": 0,
						"5": 6,
						"6": 0,
						"8": 0,
					},
					moneyToCollect: 0,
					enabled: true,
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
				outcomeDesc: "$60!",
				special: 0,
				rewardsGive: {
					userRewards: {
						money: 60,
					},
					itemsRewards: null,
					itemsLoseRewards: null,
					money: 60,
				},
				ID: 8978,
				story: [
					"You log on to your payment portal and retrieve the proceeds from your DVD bootlegging enterprise.",
					"Thanks RoboCop.",
					"Praise be to Ace Ventura.",
					"And a tip of the hat to you too, woman from Mulan.",
				],
				timestamp: 1771191504,
				specialReward: [],
				specialRewardToOverride: [],
			},
		],
		generalInfo: {
			CDsDiff: {},
			moneyDiff: 0,
			CDs: {
				"1": 0,
				"2": 0,
				"3": 0,
				"4": 0,
				"7": 0,
				"5": 6,
				"6": 0,
				"8": 0,
			},
			lastCDType: "Horror",
		},
		skillLevelTotal: 0,
		currentLevel: 100,
		lastSubCrimeID: 11,
		lastSubCrimeIDByType: 11,
		currentUserStats: {
			attemptsTotal: 5630,
			crimesByIDAttempts: {
				"8": 4726,
				"9": 318,
				"10": 26,
				"11": 560,
			},
			crimesByIDAttemptsSucc: {
				"8": 4701,
				"9": 304,
				"10": 23,
				"11": 560,
			},
			moneyFoundTotal: 2320799,
			nerveUsed: 11862,
			successesTotal: 5588,
			critFailedTotal: 7,
			CDsCopiedTotal: 99632,
			failedTotal: 35,
			CDType1Sold: 21984,
			CDType2Sold: 16279,
			CDType3Sold: 10024,
			CDType4Sold: 11126,
			CDsSoldTotal: 99626,
			moneyMadeTotal: 2323459,
			sellMoney: 929679,
			CDType7Sold: 10004,
			CDType8Sold: 10024,
			CDType5Sold: 10157,
			CDType6Sold: 10028,
			jailedTotal: 2,
			onlineStoreCustomers: 34479.637040000096,
			onlineStoreVisits: 3085470,
			onlineMoney: 1393800,
			salesTotal: 69690,
			collectSucc: 560,
			collectTotal: 560,
			moneyMadeOnlineStore: 1393780,
			specialAmmoFoundTotal: 500,
			itemsFound: {
				"369": 1,
				"819": 1,
				"366": 1,
			},
			statsByType: {
				"2": {
					successesTotal: 0,
				},
			},
			skill: 100,
			skillLevel: 0,
			enhancer: {
				name: "High-Speed Drive",
				available: true,
			},
		},
		currentUserStatistics: [
			{
				label: "Skill",
				value: "100.00",
			},
			{
				label: "Crime type",
				value: "Counterfeiting",
			},
			{
				label: "Progression bonus",
				value: "40%",
			},
			{
				label: "Enhancer",
				value: "High-Speed Drive",
				available: true,
			},
			{
				label: "Total attempts",
				value: "5,630",
			},
			{
				label: "Successes",
				value: "5,588",
			},
			{
				label: "Fails",
				value: "35",
			},
			{
				label: "Critical fails",
				value: "7",
			},
			{
				label: "Unique outcomes",
				value: "4 \/ 4",
			},
			{
				label: "Total DVDs copied",
				value: "99,632",
			},
			{
				label: "Money made",
				value: "$2,323,459",
			},
			{
				label: "Sell DVDs earnings",
				value: "$929,679",
			},
			{
				label: "Online store earnings",
				value: "$1,393,780",
			},
			{
				label: "Copy DVDs attempts",
				value: "4701 \/ 4726",
			},
			{
				label: "Sell DVDs attempts",
				value: "304 \/ 318",
			},
			{
				label: "Store setup attempts",
				value: "23 \/ 26",
			},
			{
				label: "Collect attempts",
				value: "560 \/ 560",
			},
			{
				label: "Online store visits",
				value: "3,085,470",
			},
			{
				label: "Online store customers",
				value: "34,480",
			},
			{
				label: "Online store sales",
				value: "69,690",
			},
			{
				label: "Total DVDs sold",
				value: "99,626",
			},
			{
				label: "Action DVDs sold",
				value: "21,984",
			},
			{
				label: "Comedy DVDs sold",
				value: "16,279",
			},
			{
				label: "Drama DVDs sold",
				value: "10,024",
			},
			{
				label: "Fantasy DVDs sold",
				value: "11,126",
			},
			{
				label: "Horror DVDs sold",
				value: "10,157",
			},
			{
				label: "Romance DVDs sold",
				value: "10,028",
			},
			{
				label: "Thriller DVDs sold",
				value: "10,004",
			},
			{
				label: "Sci-Fi DVDs sold",
				value: "10,024",
			},
		],
		tutorial: null,
		outcome: {
			ID: 8978,
			result: "success",
			special: false,
			story: [
				"You log on to your payment portal and retrieve the proceeds from your DVD bootlegging enterprise.",
				"Thanks RoboCop.",
				"Praise be to Ace Ventura.",
				"And a tip of the hat to you too, woman from Mulan.",
			],
			rewards: [
				{
					type: "money",
					value: 60,
				},
			],
		},
		user: {
			playername: "DeKleineKobini",
			nerve: 3,
			money: 26421411,
			isAdmin: false,
			isUnderAttack: false,
		},
		time: 1771191504,
	},
};

const RESPONSE__GRAFFITI_1: TornInternalAttemptCrime = {
	DB: {
		currentTemplate: "GraffitiMakeCD",
		avoidStatsAndNerve: false,
		special: 0,
		additionalInfo: {
			tags: 346,
			removedTags: 0,
			reputation: 4,
			sortID: 7,
			locked: false,
			spraySelected: "Green",
			lastUsedColor: "Green",
			crimesListNeeded: true,
			cans: [
				{
					itemID: 856,
					color: "Black",
					fill: 0,
				},
				{
					itemID: 857,
					color: "Red",
					fill: 100,
				},
				{
					itemID: 858,
					color: "Pink",
					fill: 100,
				},
				{
					itemID: 859,
					color: "Purple",
					fill: 0,
				},
				{
					itemID: 860,
					color: "Blue",
					fill: 0,
				},
				{
					itemID: 861,
					color: "Green",
					fill: 3,
				},
				{
					itemID: 862,
					color: "White",
					fill: 100,
				},
				{
					itemID: 863,
					color: "Orange",
					fill: 0,
				},
			],
		},
		ID: 12389,
		timestamp: 1771191584,
		specialRewardToOverride: [],
		demMod: 0,
		crimesByType: [
			{
				currentTemplate: "GraffitiMakeCD",
				title: "East Side",
				nerve: 3,
				iconClass: "east_side",
				crimeID: 18,
				subID: null,
				sortID: 1,
				enoughNerve: 3,
				requirements: {},
				available: false,
				locked: false,
				additionalInfo: {
					tags: 412,
					removedTags: 0,
					reputation: 4,
					sortID: 1,
					locked: false,
					spraySelected: null,
					lastUsedColor: "Green",
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "GraffitiMakeCD",
				title: "West Side",
				nerve: 3,
				iconClass: "west_side",
				crimeID: 12,
				subID: null,
				sortID: 2,
				enoughNerve: 3,
				requirements: {},
				available: false,
				locked: false,
				additionalInfo: {
					tags: 402,
					removedTags: 0,
					reputation: 4,
					sortID: 2,
					locked: false,
					spraySelected: null,
					lastUsedColor: "Red",
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "GraffitiMakeCD",
				title: "North Side",
				nerve: 3,
				iconClass: "north_side",
				crimeID: 13,
				subID: null,
				sortID: 3,
				enoughNerve: 3,
				requirements: {},
				available: false,
				locked: false,
				additionalInfo: {
					tags: 415,
					removedTags: 0,
					reputation: 4,
					sortID: 3,
					locked: false,
					spraySelected: null,
					lastUsedColor: "Pink",
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "GraffitiMakeCD",
				title: "Residential District",
				nerve: 3,
				iconClass: "residential",
				crimeID: 15,
				subID: null,
				sortID: 4,
				enoughNerve: 3,
				requirements: {},
				available: false,
				locked: false,
				additionalInfo: {
					tags: 386,
					removedTags: 0,
					reputation: 4,
					sortID: 4,
					locked: false,
					spraySelected: null,
					lastUsedColor: "Purple",
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "GraffitiMakeCD",
				title: "Red-Light District",
				nerve: 3,
				iconClass: "red_light",
				crimeID: 14,
				subID: null,
				sortID: 5,
				enoughNerve: 3,
				requirements: {},
				available: false,
				locked: false,
				additionalInfo: {
					tags: 3316,
					removedTags: 0,
					reputation: 5,
					sortID: 5,
					locked: false,
					spraySelected: null,
					lastUsedColor: "Blue",
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "GraffitiMakeCD",
				title: "Financial District",
				nerve: 3,
				iconClass: "financial",
				crimeID: 17,
				subID: null,
				sortID: 6,
				enoughNerve: 3,
				requirements: {},
				available: false,
				locked: false,
				additionalInfo: {
					tags: 332,
					removedTags: 0,
					reputation: 4,
					sortID: 6,
					locked: false,
					spraySelected: null,
					lastUsedColor: "White",
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
			},
			{
				currentTemplate: "GraffitiMakeCD",
				title: "City Center",
				nerve: 3,
				iconClass: "city_centre",
				crimeID: 16,
				subID: null,
				sortID: 7,
				enoughNerve: 3,
				requirements: {},
				available: false,
				locked: false,
				additionalInfo: {
					tags: 346,
					removedTags: 0,
					reputation: 4,
					sortID: 7,
					locked: false,
					spraySelected: "Green",
					lastUsedColor: "Green",
					crimesListNeeded: true,
				},
				secretsAvailable: 0,
				result: "info",
				avoidStatsAndNerve: false,
				outcomeDesc: "",
				special: 0,
				rewardsGive: {
					itemsRewards: null,
					itemsLoseRewards: null,
				},
				ID: 12389,
				story: [
					"There's a short tunnel running underneath the coastal highway just by the committee building.",
					"They must've built this so those bozos can access the bay and cleanse themselves from the stench of corruption.",
					"You head down into the tunnel and light the place up with a wall-to-wall blockbuster.",
					"Returning to the committee side entrance, you give the tunnel a new name by painting up on the surrounding walls.",
					'From this day forth, this shall be known as the "Firewalk Walkway."',
				],
				timestamp: 1771191584,
				specialReward: {
					type: "other",
					value: "City Center reputation increased",
					textTablet: "Reputation increased",
				},
				specialRewardToOverride: [],
			},
		],
		generalInfo: {
			cans: [
				{
					itemID: 856,
					color: "Black",
					fill: 0,
				},
				{
					itemID: 857,
					color: "Red",
					fill: 100,
				},
				{
					itemID: 858,
					color: "Pink",
					fill: 100,
				},
				{
					itemID: 859,
					color: "Purple",
					fill: 0,
				},
				{
					itemID: 860,
					color: "Blue",
					fill: 0,
				},
				{
					itemID: 861,
					color: "Green",
					fill: 3,
				},
				{
					itemID: 862,
					color: "White",
					fill: 100,
				},
				{
					itemID: 863,
					color: "Orange",
					fill: 0,
				},
			],
			lastUsedColor: "Green",
		},
		skillLevelTotal: 0,
		currentLevel: 100,
		lastSubCrimeID: 16,
		lastSubCrimeIDByType: 16,
		currentUserStats: {
			attemptsTotal: 11394,
			crimesByIDAttempts: {
				"18": 1056,
				"12": 977,
				"13": 952,
				"15": 808,
				"14": 5579,
				"17": 1019,
				"16": 1003,
			},
			crimesByIDAttemptsSucc: {
				"18": 1041,
				"12": 967,
				"13": 938,
				"15": 796,
				"14": 5500,
				"17": 989,
				"16": 985,
			},
			graffitiMade18: 1041,
			moneyFoundTotal: 15158698,
			mostGraffitiInArea18: 504,
			mostGraffitiInOneArea: 4022,
			nerveUsed: 34182,
			successesTotal: 11216,
			itemsFound: {
				"863": 5,
				"180": 24,
				"220": 4,
				"242": 8,
				"392": 6,
				"856": 5,
				"979": 1,
				"66": 10,
				"980": 1,
				"981": 1,
				"860": 7,
				"67": 2,
				"68": 6,
				"438": 1,
				"859": 10,
				"246": 5,
				"196": 12,
				"197": 1,
				"198": 1,
				"203": 2,
				"205": 6,
				"175": 1,
				"226": 1,
				"33": 1,
				"565": 1,
				"956": 20,
				"861": 8,
				"1125": 25,
				"365": 2,
				"204": 2,
				"985": 1,
				"361": 1,
				"858": 17,
				"201": 1,
				"857": 88,
				"200": 2,
				"731": 2,
				"742": 4,
				"294": 4,
				"426": 4,
				"531": 2,
				"550": 2,
			},
			failedTotal: 163,
			graffitiMade12: 967,
			mostGraffitiInArea12: 501,
			cansUsed: 268,
			critFailedTotal: 15,
			costToCity: 1328959,
			graffitiRemoved: 2857,
			graffitiMade13: 938,
			mostGraffitiInArea13: 551,
			graffitiMade15: 796,
			mostGraffitiInArea15: 501,
			graffitiMade14: 5500,
			mostGraffitiInArea14: 4022,
			specialAmmoFoundTotal: 1200,
			graffitiMade17: 989,
			mostGraffitiInArea17: 509,
			graffitiMade16: 985,
			mostGraffitiInArea16: 500,
			jailedTotal: 12,
			statsByType: {
				"3": {
					successesTotal: 0,
				},
			},
			skill: 100,
			skillLevel: 0,
			enhancer: {
				name: "Paint Mask",
				available: true,
			},
		},
		currentUserStatistics: [
			{
				label: "Skill",
				value: "100.00",
			},
			{
				label: "Crime type",
				value: "Vandalism",
			},
			{
				label: "Progression bonus",
				value: "40%",
			},
			{
				label: "Enhancer",
				value: "Paint Mask",
				available: true,
			},
			{
				label: "Total attempts",
				value: "11,394",
			},
			{
				label: "Successes",
				value: "11,216",
			},
			{
				label: "Fails",
				value: "163",
			},
			{
				label: "Critical fails",
				value: "15",
			},
			{
				label: "Unique outcomes",
				value: "41 \/ 41",
			},
			{
				label: "Money earned",
				value: "$15,158,698",
			},
			{
				label: "East Side",
				value: "1,041 \/ 1,056",
			},
			{
				label: "West Side",
				value: "967 \/ 977",
			},
			{
				label: "North Side",
				value: "938 \/ 952",
			},
			{
				label: "Residential District",
				value: "796 \/ 808",
			},
			{
				label: "Red-Light District",
				value: "5,500 \/ 5,579",
			},
			{
				label: "Financial District",
				value: "989 \/ 1,019",
			},
			{
				label: "City Center",
				value: "985 \/ 1,003",
			},
			{
				label: "Cans of Spray Paint used",
				value: "268",
			},
			{
				label: "Most graffiti in one area",
				value: "4,022",
			},
			{
				label: "Most simultaneous graffiti",
				value: "7,088",
			},
			{
				label: "Graffiti removed",
				value: "2,857",
			},
			{
				label: "Cost to city",
				value: "$1,328,959",
			},
			{
				label: "Total items found",
				value: "307",
			},
			{
				label: "Blank DVDs",
				value: "20",
			},
			{
				label: "Bottle of Beer",
				value: "24",
			},
			{
				label: "Bottle of Kandy Kane",
				value: "2",
			},
			{
				label: "Bottle of Pumpkin Brew",
				value: "2",
			},
			{
				label: "Bottle of Sake",
				value: "4",
			},
			{
				label: "Bottle of Tequila",
				value: "4",
			},
			{
				label: "Box of Medical Supplies",
				value: "2",
			},
			{
				label: "Can of Goose Juice",
				value: "1",
			},
			{
				label: "Cannabis",
				value: "12",
			},
			{
				label: "Card Skimmer",
				value: "25",
			},
			{
				label: "Cricket Bat",
				value: "1",
			},
			{
				label: "Ecstasy",
				value: "1",
			},
			{
				label: "Empty Blood Bag",
				value: "2",
			},
			{
				label: "Fireworks",
				value: "5",
			},
			{
				label: "First Aid Kit",
				value: "2",
			},
			{
				label: "Grenade",
				value: "4",
			},
			{
				label: "HEG",
				value: "8",
			},
			{
				label: "High-Speed Drive",
				value: "1",
			},
			{
				label: "Ketamine",
				value: "1",
			},
			{
				label: "Ladder",
				value: "1",
			},
			{
				label: "Molotov Cocktail",
				value: "4",
			},
			{
				label: "Morphine",
				value: "10",
			},
			{
				label: "Neumune Tablet",
				value: "1",
			},
			{
				label: "Opium",
				value: "2",
			},
			{
				label: "PCP",
				value: "1",
			},
			{
				label: "Paint Mask",
				value: "1",
			},
			{
				label: "Pepper Spray",
				value: "6",
			},
			{
				label: "Police Vest",
				value: "1",
			},
			{
				label: "Shrooms",
				value: "2",
			},
			{
				label: "Small First Aid Kit",
				value: "6",
			},
			{
				label: "Smoke Grenade",
				value: "1",
			},
			{
				label: "Speed",
				value: "2",
			},
			{
				label: "Spray Paint : Black",
				value: "5",
			},
			{
				label: "Spray Paint : Blue",
				value: "7",
			},
			{
				label: "Spray Paint : Green",
				value: "8",
			},
			{
				label: "Spray Paint : Orange",
				value: "5",
			},
			{
				label: "Spray Paint : Pink",
				value: "17",
			},
			{
				label: "Spray Paint : Purple",
				value: "10",
			},
			{
				label: "Spray Paint : Red",
				value: "88",
			},
			{
				label: "Taser",
				value: "1",
			},
			{
				label: "Vicodin",
				value: "6",
			},
			{
				label: "Wire Cutters",
				value: "1",
			},
		],
		tutorial: null,
		outcome: {
			ID: 12389,
			result: "success",
			special: false,
			story: [
				"There's a short tunnel running underneath the coastal highway just by the committee building.",
				"They must've built this so those bozos can access the bay and cleanse themselves from the stench of corruption.",
				"You head down into the tunnel and light the place up with a wall-to-wall blockbuster.",
				"Returning to the committee side entrance, you give the tunnel a new name by painting up on the surrounding walls.",
				'From this day forth, this shall be known as the "Firewalk Walkway."',
			],
			rewards: [
				{
					type: "other",
					textTablet: "Reputation increased",
					text: "City Center reputation increased",
				},
			],
		},
		user: {
			playername: "DeKleineKobini",
			nerve: 0,
			money: 26421411,
			isAdmin: false,
			isUnderAttack: false,
		},
		time: 1771191584,
	},
};

const RESPONSE__BURGLARY_1: TornInternalAttemptCrime = {
	DB: {
		infoByTypeGroup: "burgleBurglary",
		typeGroupSubs: false,
		isInfoByTypeArray: true,
		avoidStatsAndNerve: false,
		special: 0,
		additionalInfo: {
			crimesListNeeded: true,
		},
		ID: 10953,
		timestamp: 1771190457,
		specialRewardToOverride: [],
		demMod: 0,
		crimesByType: {
			scout: {
				lastActiveArea: 68,
				title: "Scout for targets",
				iconClass: "scout",
				nerve: 3,
				nerveFocus: 9,
				requirements: {
					minCrimeLevel: {
						value: 50,
						available: true,
					},
				},
				buttonTitle: "Scout",
				lastScoutedArea: 68,
				lastResidentialFocus: null,
				lastCommercialFocus: null,
				lastIndustrialFocus: 129,
				areas: [
					{
						title: "Industrial targets",
						crimeID: 68,
						available: true,
						secretsAvailable: 0,
						successChance: null,
						requirements: {
							minCrimeLevel: {
								value: 50,
								available: true,
							},
						},
					},
					{
						title: "Commercial targets",
						crimeID: 67,
						available: true,
						secretsAvailable: 0,
						successChance: null,
						requirements: {
							minCrimeLevel: {
								value: 25,
								available: true,
							},
						},
					},
					{
						title: "Residential targets",
						crimeID: 66,
						available: true,
						secretsAvailable: 0,
						successChance: null,
					},
				],
				available: true,
			},
			properties: [
				{
					title: "Slaughterhouse",
					tabletTitle: "Slaughterhouse",
					mobileTitle: "Slaughterhouse",
					burgleCrimeID: 130,
					caseCrimeID: 129,
					burgleNerve: 6,
					caseNerve: 2,
					burgleAvailable: true,
					caseAvailable: true,
					subID: "69922d9a2dfc4567242960",
					confidence: 31,
					safetyStatus: "unknown",
					created: 1771187610018837,
					successChance: null,
					recommendedItem: {
						ID: 1084,
						title: "Credit card",
						owned: true,
					},
					expire: 1771446811,
					expiresSoon: false,
					statusExpire: 1771189780,
					statusStarted: 1771187611,
					caseSecretsAvailable: 0,
					burgleSecretsAvailable: 0,
				},
				{
					title: "Slaughterhouse",
					tabletTitle: "Slaughterhouse",
					mobileTitle: "Slaughterhouse",
					burgleCrimeID: 130,
					caseCrimeID: 129,
					burgleNerve: 6,
					caseNerve: 2,
					burgleAvailable: false,
					caseAvailable: false,
					subID: "69922d981a8ce901094080",
					confidence: 31,
					safetyStatus: "dangerous",
					created: 1771187608010877.2,
					successChance: null,
					recommendedItem: {
						ID: 1084,
						title: "Credit card",
						owned: true,
					},
					expire: 1771446809,
					expiresSoon: false,
					statusExpire: 1771191177,
					statusStarted: 1771187609,
					caseSecretsAvailable: 0,
					burgleSecretsAvailable: 0,
				},
				{
					title: "Slaughterhouse",
					tabletTitle: "Slaughterhouse",
					mobileTitle: "Slaughterhouse",
					burgleCrimeID: 130,
					caseCrimeID: 129,
					burgleNerve: 6,
					caseNerve: 2,
					burgleAvailable: true,
					caseAvailable: true,
					subID: "6991acd21365b636462372",
					confidence: 0,
					safetyStatus: "unknown",
					created: 1771154642007946.5,
					successChance: null,
					recommendedItem: {
						ID: 1084,
						title: "Credit card",
						owned: true,
					},
					expire: 1771446748,
					expiresSoon: false,
					statusExpire: 1771189711,
					statusStarted: 1771187548,
					caseSecretsAvailable: 0,
					burgleSecretsAvailable: 0,
				},
				{
					title: "Slaughterhouse",
					tabletTitle: "Slaughterhouse",
					mobileTitle: "Slaughterhouse",
					burgleCrimeID: 130,
					caseCrimeID: 129,
					burgleNerve: 6,
					caseNerve: 2,
					burgleAvailable: true,
					caseAvailable: true,
					subID: "6991acd0147b7006728970",
					confidence: 0,
					safetyStatus: "unknown",
					created: 1771154640008392.8,
					successChance: null,
					recommendedItem: {
						ID: 1084,
						title: "Credit card",
						owned: true,
					},
					expire: 1771446748,
					expiresSoon: false,
					statusExpire: 1771189728,
					statusStarted: 1771187548,
					caseSecretsAvailable: 0,
					burgleSecretsAvailable: 0,
				},
			],
			focusedScoutingIDs: {
				"66": [69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91],
				"67": [93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113],
				"68": [115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135],
			},
			burgleAreas: {
				"69": "Tool Shed",
				"71": "Beach Hut",
				"73": "Mobile Home",
				"75": "Bungalow",
				"77": "Cottage",
				"79": "Apartment",
				"81": "Suburban Home",
				"83": "Secluded Cabin",
				"85": "Farmhouse",
				"87": "Lake House",
				"89": "Luxury Villa",
				"91": "Manor House",
				"93": "Self Storage Facility",
				"95": "Postal Office",
				"97": "Funeral Parlor",
				"99": "Market",
				"101": "Cleaning Agency",
				"103": "Barbershop",
				"105": "Liquor Store",
				"107": "Dentists Office",
				"109": "Chiropractors",
				"111": "Recruitment Agency",
				"113": "Advertising Agency",
				"115": "Shipyard",
				"117": "Dockside Warehouse",
				"119": "Farm Storage Unit",
				"121": "Printing Works",
				"123": "Brewery",
				"125": "Truckyard",
				"127": "Old Factory",
				"129": "Slaughterhouse",
				"131": "Paper Mill",
				"133": "Foundry",
				"135": "Fertilizer Plant",
			},
			availableForFocus: [
				69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131,
				133, 135,
			],
		},
		skillLevelTotal: 0,
		currentLevel: 100,
		lastSubCrimeID: 130,
		lastSubCrimeIDByType: 130,
		currentUserStats: {
			attemptsTotal: 19200,
			crimesByIDAttempts: {
				"66": 1932,
				"75": 63,
				"76": 40,
				"74": 40,
				"71": 1769,
				"72": 1416,
				"73": 63,
				"69": 48,
				"70": 35,
				"77": 74,
				"78": 47,
				"79": 122,
				"80": 49,
				"81": 65,
				"82": 38,
				"67": 1197,
				"97": 69,
				"98": 38,
				"95": 101,
				"93": 129,
				"94": 42,
				"83": 43,
				"84": 46,
				"96": 35,
				"99": 152,
				"101": 88,
				"102": 48,
				"103": 67,
				"104": 50,
				"100": 43,
				"85": 51,
				"86": 66,
				"105": 31,
				"106": 29,
				"87": 61,
				"88": 40,
				"68": 2458,
				"119": 224,
				"117": 344,
				"118": 104,
				"115": 389,
				"116": 99,
				"120": 94,
				"107": 84,
				"108": 53,
				"122": 84,
				"121": 210,
				"110": 40,
				"109": 56,
				"123": 578,
				"124": 171,
				"125": 227,
				"126": 128,
				"90": 11,
				"127": 161,
				"128": 109,
				"111": 85,
				"112": 16,
				"89": 26,
				"129": 3024,
				"130": 1824,
				"131": 114,
				"132": 48,
				"133": 48,
				"134": 20,
				"135": 17,
				"136": 7,
				"113": 28,
				"114": 6,
				"91": 76,
				"92": 10,
			},
			crimesByIDAttemptsSucc: {
				"66": 1932,
				"75": 53,
				"76": 34,
				"71": 1391,
				"72": 1359,
				"73": 54,
				"74": 37,
				"69": 36,
				"70": 27,
				"77": 66,
				"78": 42,
				"79": 94,
				"80": 35,
				"81": 47,
				"82": 30,
				"67": 1197,
				"97": 60,
				"98": 30,
				"95": 73,
				"93": 105,
				"94": 34,
				"83": 32,
				"96": 27,
				"84": 34,
				"101": 67,
				"99": 111,
				"103": 60,
				"104": 40,
				"100": 31,
				"85": 43,
				"86": 51,
				"102": 37,
				"105": 26,
				"106": 21,
				"87": 45,
				"88": 31,
				"68": 2458,
				"119": 175,
				"117": 282,
				"118": 73,
				"115": 316,
				"116": 72,
				"120": 71,
				"107": 65,
				"108": 45,
				"122": 69,
				"121": 183,
				"110": 30,
				"109": 48,
				"123": 454,
				"124": 137,
				"125": 178,
				"126": 108,
				"90": 8,
				"127": 136,
				"128": 93,
				"111": 70,
				"112": 14,
				"89": 23,
				"129": 2432,
				"130": 1639,
				"131": 89,
				"132": 44,
				"133": 37,
				"134": 18,
				"135": 16,
				"136": 6,
				"113": 19,
				"114": 6,
				"91": 56,
				"92": 10,
			},
			moneyFoundTotal: 5081314,
			nerveUsed: 84297,
			successesTotal: 16872,
			itemsFound: {
				"1219": 14,
				"67": 70,
				"1251": 39,
				"18": 5,
				"48": 15,
				"905": 50,
				"15": 4,
				"10": 58,
				"1096": 15,
				"1222": 47,
				"104": 12,
				"65": 13,
				"1200": 13,
				"1274": 14,
				"426": 76,
				"634": 2,
				"51": 60,
				"52": 6,
				"55": 15,
				"1201": 37,
				"1088": 3,
				"199": 122,
				"621": 104,
				"1082": 62,
				"1214": 178,
				"46": 57,
				"1231": 2,
				"205": 61,
				"183": 12,
				"6": 64,
				"97": 8,
				"1211": 20,
				"1244": 5,
				"209": 2,
				"310": 14,
				"35": 2,
				"1210": 7,
				"1276": 8,
				"1094": 13,
				"1095": 4,
				"1320": 4,
				"200": 8,
				"1240": 29,
				"392": 18,
				"650": 14,
				"180": 918,
				"393": 44,
				"431": 8,
				"643": 23,
				"645": 26,
				"1084": 14,
				"11": 2,
				"279": 2,
				"53": 5,
				"60": 10,
				"1087": 40,
				"1273": 5,
				"1081": 54,
				"626": 50,
				"1212": 274,
				"1266": 78,
				"1269": 16,
				"527": 61,
				"1236": 68,
				"62": 74,
				"1255": 61,
				"1292": 589,
				"1313": 1,
				"731": 322,
				"1281": 12,
				"43": 12,
				"550": 57,
				"892": 11,
				"47": 56,
				"42": 60,
				"1083": 14,
				"359": 4,
				"154": 92,
				"417": 20,
				"59": 10,
				"1285": 4,
				"247": 3,
				"33": 7,
				"129": 3,
				"4": 5,
				"907": 52,
				"930": 4,
				"939": 1,
				"1202": 21,
				"196": 420,
				"909": 59,
				"568": 9,
				"41": 25,
				"1226": 9,
				"1233": 15,
				"32": 5,
				"791": 1,
				"1232": 19,
				"886": 71,
				"369": 1,
				"934": 1,
				"96": 1,
				"928": 53,
				"936": 53,
				"197": 53,
				"437": 12,
				"20": 8,
				"231": 3,
				"411": 3,
				"619": 2,
				"438": 3,
				"646": 5,
				"58": 1,
				"176": 1,
				"218": 4,
				"1203": 6,
				"1215": 9,
				"1216": 6,
				"422": 10,
				"1223": 5,
				"64": 19,
				"181": 99,
				"1265": 84,
				"1282": 24,
				"1189": 484,
				"372": 541,
				"159": 24,
				"3": 24,
				"950": 2,
				"54": 15,
				"39": 14,
				"1085": 17,
				"894": 7,
				"1258": 13,
				"8": 87,
				"432": 128,
				"19": 7,
				"1123": 16,
				"44": 16,
				"1217": 72,
				"897": 416,
				"249": 3,
				"416": 1,
				"57": 3,
				"1235": 39,
				"56": 3,
				"1316": 3,
				"408": 43,
				"45": 22,
				"703": 2,
				"1280": 9,
				"1089": 3,
				"1277": 34,
				"567": 1,
				"294": 20,
				"904": 9,
				"985": 2,
				"1239": 5,
				"1248": 33,
				"542": 19,
				"1314": 4,
				"1327": 16,
				"1328": 1,
				"1329": 2,
				"440": 7,
				"414": 2,
				"5": 3,
				"66": 26,
				"887": 29,
				"61": 9,
				"1209": 3,
				"110": 3,
				"1221": 2,
				"187": 6,
				"1": 14,
				"1331": 5,
				"1207": 1,
				"899": 1,
				"1242": 369,
				"402": 2,
				"413": 2,
				"622": 44,
				"625": 98,
				"531": 46,
				"252": 2,
				"28": 6,
				"859": 5,
				"860": 2,
				"861": 8,
				"862": 64,
				"415": 4,
				"38": 27,
				"236": 9,
				"707": 100,
				"1261": 15,
				"1262": 241,
				"1263": 5,
				"365": 20,
				"206": 10,
				"616": 104,
				"1253": 32,
				"1259": 20,
				"270": 67,
				"172": 36,
				"1204": 4,
				"230": 56,
				"368": 1,
				"560": 2,
				"1208": 33,
				"407": 44,
				"68": 62,
				"246": 4,
				"552": 4,
				"198": 460,
				"226": 6,
				"1247": 1,
				"868": 42,
				"1268": 33,
				"182": 495,
				"177": 6,
				"436": 49,
				"379": 23,
				"601": 1,
				"1272": 15,
				"943": 5,
				"949": 5,
				"378": 10,
				"215": 35,
				"241": 3,
				"1256": 115,
				"1288": 126,
				"1330": 4,
				"34": 6,
				"328": 3,
				"406": 61,
				"409": 67,
				"1264": 390,
				"1286": 19,
				"889": 6,
				"1227": 26,
				"1230": 10,
				"244": 2,
				"201": 2,
				"565": 1,
				"956": 3,
				"1351": 1,
				"1238": 1,
				"1241": 1,
				"335": 47,
				"1278": 1,
				"535": 1,
				"1279": 2,
				"1260": 1,
				"1092": 12,
				"1220": 23,
				"574": 1,
				"895": 37,
				"232": 2,
				"562": 2,
				"623": 99,
				"941": 2,
				"227": 54,
				"1284": 4,
				"1249": 16,
				"1270": 44,
				"49": 7,
				"190": 9,
				"257": 5,
				"1228": 170,
				"2": 4,
				"262": 11,
				"948": 3,
				"175": 62,
				"817": 5,
				"875": 40,
				"256": 40,
				"1257": 11,
				"366": 2,
				"36": 6,
				"1287": 9,
				"1289": 19,
				"1252": 106,
				"885": 143,
				"981": 7,
				"557": 4,
				"1315": 1,
				"944": 20,
				"401": 16,
				"210": 4,
				"429": 4,
				"529": 11,
				"530": 1,
				"884": 6,
				"927": 10,
				"1290": 29,
				"439": 3,
				"649": 2,
				"1250": 1,
				"1283": 4,
				"412": 2,
				"1078": 4,
				"248": 6,
				"403": 4,
				"1254": 11,
				"222": 20,
				"1213": 8,
				"541": 8,
				"327": 3,
				"1205": 9,
				"1317": 3,
				"624": 6,
				"938": 5,
				"951": 5,
				"952": 5,
				"1318": 52,
				"364": 1,
				"111": 1,
				"239": 1,
				"278": 2,
				"37": 4,
				"1234": 113,
				"1347": 20,
				"1275": 6,
				"647": 2,
				"888": 2,
				"856": 7,
				"857": 69,
				"858": 67,
				"863": 4,
				"1321": 6,
				"1322": 6,
				"380": 1,
				"640": 4,
				"1291": 1,
				"394": 6,
				"204": 4,
				"1332": 2,
				"358": 45,
				"980": 2,
				"7": 59,
				"1319": 2,
				"1334": 1,
				"1338": 1,
				"233": 1,
				"603": 2,
				"280": 1,
				"559": 1,
				"620": 1,
				"1225": 1,
				"275": 1,
				"1199": 1,
				"580": 14,
				"377": 24,
				"16": 66,
				"1243": 1,
				"1246": 3,
				"1267": 10,
				"613": 1,
				"146": 1,
				"410": 2,
				"544": 1,
				"173": 1,
				"1206": 1,
				"986": 2,
				"575": 1,
				"890": 2,
				"896": 1,
				"419": 1,
				"463": 1,
				"633": 1,
				"265": 8,
				"391": 2,
				"151": 2,
				"40": 5,
				"434": 1,
				"1245": 1,
				"189": 1,
				"229": 1,
				"489": 1,
				"641": 1,
				"404": 1,
				"1301": 4,
				"1302": 1,
				"1125": 1,
				"902": 1,
				"903": 1,
				"1340": 1,
				"528": 4,
				"1086": 1,
				"1124": 2,
				"929": 1,
				"933": 1,
				"942": 1,
				"1237": 1,
				"220": 2,
				"225": 1,
				"1457": 1,
				"12": 38,
				"906": 38,
				"1362": 14,
				"430": 1,
				"1462": 4,
				"1458": 140,
				"1463": 3,
				"1460": 356,
				"814": 16,
				"400": 65,
				"576": 61,
			},
			critFailedTotal: 94,
			jailedTotal: 207,
			failedTotal: 2234,
			ammoFoundTotal: 1440,
			specialAmmoFoundTotal: 1075,
			focusedScouting: {
				"121": 1,
				"117": 5,
				"71": 1335,
				"133": 6,
				"123": 12,
				"129": 1628,
			},
			statsByType: {
				"7": {
					successesTotal: 0,
				},
			},
			skill: 100,
			skillLevel: 0,
			enhancer: {
				name: "Flashlight",
				available: true,
			},
		},
		currentUserStatistics: [
			{
				label: "Skill",
				value: "100.00",
			},
			{
				label: "Crime type",
				value: "Theft",
			},
			{
				label: "Progression bonus",
				value: "40%",
			},
			{
				label: "Enhancer",
				value: "Flashlight",
				available: true,
			},
			{
				label: "Total attempts",
				value: "19,200",
			},
			{
				label: "Successes",
				value: "16,872",
			},
			{
				label: "Fails",
				value: "2,234",
			},
			{
				label: "Critical fails",
				value: "94",
			},
			{
				label: "Unique outcomes",
				value: "34 \/ 34",
			},
			{
				label: "Distinct targets burgled",
				value: "34 \/ 34",
			},
			{
				label: "Residential targets scouted",
				value: "1,932",
			},
			{
				label: "Commercial targets scouted",
				value: "1,197",
			},
			{
				label: "Industrial targets scouted",
				value: "2,458",
			},
			{
				label: "Targets cased",
				value: "6,942 \/ 8,687",
			},
			{
				label: "Targets burgled",
				value: "4,343 \/ 4,926",
			},
			{
				label: "Money burgled",
				value: "$5,081,314",
			},
			{
				label: "Total items burgled",
				value: "14,170",
			},
			{
				label: "Ammo burgled",
				value: "1,440",
			},
			{
				label: "Special ammo burgled",
				value: "1,075",
			},
			{
				label: "Advertising Agency cased",
				value: "19 \/ 28",
			},
			{
				label: "Advertising Agency burgled",
				value: "6 \/ 6",
			},
			{
				label: "Apartment cased",
				value: "94 \/ 122",
			},
			{
				label: "Apartment burgled",
				value: "35 \/ 49",
			},
			{
				label: "Barbershop cased",
				value: "60 \/ 67",
			},
			{
				label: "Barbershop burgled",
				value: "40 \/ 50",
			},
			{
				label: "Beach Hut cased",
				value: "1391 \/ 1769",
			},
			{
				label: "Beach Hut burgled",
				value: "1359 \/ 1416",
			},
			{
				label: "Brewery cased",
				value: "454 \/ 578",
			},
			{
				label: "Brewery burgled",
				value: "137 \/ 171",
			},
			{
				label: "Bungalow cased",
				value: "53 \/ 63",
			},
			{
				label: "Bungalow burgled",
				value: "34 \/ 40",
			},
			{
				label: "Chiropractors cased",
				value: "48 \/ 56",
			},
			{
				label: "Chiropractors burgled",
				value: "30 \/ 40",
			},
			{
				label: "Cleaning Agency cased",
				value: "67 \/ 88",
			},
			{
				label: "Cleaning Agency burgled",
				value: "37 \/ 48",
			},
			{
				label: "Cottage cased",
				value: "66 \/ 74",
			},
			{
				label: "Cottage burgled",
				value: "42 \/ 47",
			},
			{
				label: "Dentists Office cased",
				value: "65 \/ 84",
			},
			{
				label: "Dentists Office burgled",
				value: "45 \/ 53",
			},
			{
				label: "Dockside Warehouse cased",
				value: "282 \/ 344",
			},
			{
				label: "Dockside Warehouse burgled",
				value: "73 \/ 104",
			},
			{
				label: "Farm Storage Unit cased",
				value: "175 \/ 224",
			},
			{
				label: "Farm Storage Unit burgled",
				value: "71 \/ 94",
			},
			{
				label: "Farmhouse cased",
				value: "43 \/ 51",
			},
			{
				label: "Farmhouse burgled",
				value: "51 \/ 66",
			},
			{
				label: "Fertilizer Plant cased",
				value: "16 \/ 17",
			},
			{
				label: "Fertilizer Plant burgled",
				value: "6 \/ 7",
			},
			{
				label: "Foundry cased",
				value: "37 \/ 48",
			},
			{
				label: "Foundry burgled",
				value: "18 \/ 20",
			},
			{
				label: "Funeral Parlor cased",
				value: "60 \/ 69",
			},
			{
				label: "Funeral Parlor burgled",
				value: "30 \/ 38",
			},
			{
				label: "Lake House cased",
				value: "45 \/ 61",
			},
			{
				label: "Lake House burgled",
				value: "31 \/ 40",
			},
			{
				label: "Liquor Store cased",
				value: "26 \/ 31",
			},
			{
				label: "Liquor Store burgled",
				value: "21 \/ 29",
			},
			{
				label: "Luxury Villa cased",
				value: "23 \/ 26",
			},
			{
				label: "Luxury Villa burgled",
				value: "8 \/ 11",
			},
			{
				label: "Manor House cased",
				value: "56 \/ 76",
			},
			{
				label: "Manor House burgled",
				value: "10 \/ 10",
			},
			{
				label: "Market cased",
				value: "111 \/ 152",
			},
			{
				label: "Market burgled",
				value: "31 \/ 43",
			},
			{
				label: "Mobile Home cased",
				value: "54 \/ 63",
			},
			{
				label: "Mobile Home burgled",
				value: "37 \/ 40",
			},
			{
				label: "Old Factory cased",
				value: "136 \/ 161",
			},
			{
				label: "Old Factory burgled",
				value: "93 \/ 109",
			},
			{
				label: "Paper Mill cased",
				value: "89 \/ 114",
			},
			{
				label: "Paper Mill burgled",
				value: "44 \/ 48",
			},
			{
				label: "Postal Office cased",
				value: "73 \/ 101",
			},
			{
				label: "Postal Office burgled",
				value: "27 \/ 35",
			},
			{
				label: "Printing Works cased",
				value: "183 \/ 210",
			},
			{
				label: "Printing Works burgled",
				value: "69 \/ 84",
			},
			{
				label: "Recruitment Agency cased",
				value: "70 \/ 85",
			},
			{
				label: "Recruitment Agency burgled",
				value: "14 \/ 16",
			},
			{
				label: "Secluded Cabin cased",
				value: "32 \/ 43",
			},
			{
				label: "Secluded Cabin burgled",
				value: "34 \/ 46",
			},
			{
				label: "Self Storage Facility cased",
				value: "105 \/ 129",
			},
			{
				label: "Self Storage Facility burgled",
				value: "34 \/ 42",
			},
			{
				label: "Shipyard cased",
				value: "316 \/ 389",
			},
			{
				label: "Shipyard burgled",
				value: "72 \/ 99",
			},
			{
				label: "Slaughterhouse cased",
				value: "2432 \/ 3024",
			},
			{
				label: "Slaughterhouse burgled",
				value: "1639 \/ 1824",
			},
			{
				label: "Suburban Home cased",
				value: "47 \/ 65",
			},
			{
				label: "Suburban Home burgled",
				value: "30 \/ 38",
			},
			{
				label: "Tool Shed cased",
				value: "36 \/ 48",
			},
			{
				label: "Tool Shed burgled",
				value: "27 \/ 35",
			},
			{
				label: "Truckyard cased",
				value: "178 \/ 227",
			},
			{
				label: "Truckyard burgled",
				value: "108 \/ 128",
			},
			{
				label: "Adhesive Plastic",
				value: "6",
			},
			{
				label: "Advent Calendar",
				value: "4",
			},
			{
				label: "Afro Comb",
				value: "61",
			},
			{
				label: "Ammonia",
				value: "33",
			},
			{
				label: "Anchor",
				value: "1",
			},
			{
				label: "Axe",
				value: "87",
			},
			{
				label: "BT MP9",
				value: "1",
			},
			{
				label: "Bag of Bloody Eyeballs",
				value: "2",
			},
			{
				label: "Bag of Bon Bons",
				value: "4",
			},
			{
				label: "Bag of Candy Kisses",
				value: "61",
			},
			{
				label: "Bag of Chocolate Kisses",
				value: "4",
			},
			{
				label: "Bag of Chocolate Truffles",
				value: "11",
			},
			{
				label: "Bag of Tootsie Rolls",
				value: "4",
			},
			{
				label: "Bandana",
				value: "1",
			},
			{
				label: "Baseball Bat",
				value: "4",
			},
			{
				label: "Baseball Cap",
				value: "10",
			},
			{
				label: "Beach Ball",
				value: "33",
			},
			{
				label: "Benelli M4 Super",
				value: "6",
			},
			{
				label: "Beretta M9",
				value: "4",
			},
			{
				label: "Bermudas",
				value: "53",
			},
			{
				label: "Big Box of Chocolate Bars",
				value: "6",
			},
			{
				label: "Bikini",
				value: "6",
			},
			{
				label: "Binoculars",
				value: "13",
			},
			{
				label: "Birthday Wrapping Paper",
				value: "24",
			},
			{
				label: "Blank Casino Chips",
				value: "3",
			},
			{
				label: "Blank DVDs",
				value: "3",
			},
			{
				label: "Blank DVDs : 100",
				value: "16",
			},
			{
				label: "Blanket",
				value: "39",
			},
			{
				label: "Bleach",
				value: "274",
			},
			{
				label: "Bleaching Tray",
				value: "4",
			},
			{
				label: "Bloody Apron",
				value: "1",
			},
			{
				label: "Blouse",
				value: "1",
			},
			{
				label: "Blowgun",
				value: "2",
			},
			{
				label: "Blowtorch",
				value: "4",
			},
			{
				label: "Boat Engine",
				value: "39",
			},
			{
				label: "Bolt Cutters",
				value: "24",
			},
			{
				label: "Bond Paper",
				value: "170",
			},
			{
				label: "Bone",
				value: "589",
			},
			{
				label: "Bone Saw",
				value: "61",
			},
			{
				label: "Boob Tube",
				value: "4",
			},
			{
				label: "Bottle Cap",
				value: "416",
			},
			{
				label: "Bottle of Beer",
				value: "918",
			},
			{
				label: "Bottle of Champagne",
				value: "99",
			},
			{
				label: "Bottle of Kandy Kane",
				value: "57",
			},
			{
				label: "Bottle of Mistletoe Madness",
				value: "4",
			},
			{
				label: "Bottle of Pumpkin Brew",
				value: "46",
			},
			{
				label: "Bottle of Sake",
				value: "20",
			},
			{
				label: "Bottle of Stinky Swamp Punch",
				value: "8",
			},
			{
				label: "Bottle of Tequila",
				value: "76",
			},
			{
				label: "Bottle of Wicked Witch",
				value: "19",
			},
			{
				label: "Bowling Trophy",
				value: "1",
			},
			{
				label: "Box of Bon Bons",
				value: "27",
			},
			{
				label: "Box of Chocolate Bars",
				value: "2",
			},
			{
				label: "Box of Extra Strong Mints",
				value: "14",
			},
			{
				label: "Box of Grenades",
				value: "1",
			},
			{
				label: "Box of Medical Supplies",
				value: "20",
			},
			{
				label: "Box of Sweet Hearts",
				value: "2",
			},
			{
				label: "Box of Tissues",
				value: "4",
			},
			{
				label: "Brass Ingot",
				value: "106",
			},
			{
				label: "Brick",
				value: "6",
			},
			{
				label: "Broom",
				value: "8",
			},
			{
				label: "Bucket",
				value: "15",
			},
			{
				label: "Bull Semen",
				value: "1",
			},
			{
				label: "Bulletproof Vest",
				value: "6",
			},
			{
				label: "Bunch of Carnations",
				value: "1",
			},
			{
				label: "Bunch of Flowers",
				value: "8",
			},
			{
				label: "Bushmaster Carbon 15",
				value: "3",
			},
			{
				label: "Butterfly Knife",
				value: "1",
			},
			{
				label: "C4 Explosive",
				value: "9",
			},
			{
				label: "CD Player",
				value: "12",
			},
			{
				label: "CPU",
				value: "4",
			},
			{
				label: "Can of Damp Valley",
				value: "2",
			},
			{
				label: "Can of Goose Juice",
				value: "2",
			},
			{
				label: "Can of Munster",
				value: "1",
			},
			{
				label: "Candle",
				value: "52",
			},
			{
				label: "Cannabis",
				value: "420",
			},
			{
				label: "Capri Pants",
				value: "1",
			},
			{
				label: "Car Battery",
				value: "6",
			},
			{
				label: "Car Keys",
				value: "50",
			},
			{
				label: "Card Programmer",
				value: "2",
			},
			{
				label: "Card Skimmer",
				value: "1",
			},
			{
				label: "Cardigan",
				value: "1",
			},
			{
				label: "Cardstock",
				value: "6",
			},
			{
				label: "Casket",
				value: "1",
			},
			{
				label: "Cassock",
				value: "1",
			},
			{
				label: "Cattle Prod",
				value: "11",
			},
			{
				label: "Cell Phone",
				value: "15",
			},
			{
				label: "Certificate Seal",
				value: "20",
			},
			{
				label: "Chain Mail",
				value: "1",
			},
			{
				label: "Chainsaw",
				value: "58",
			},
			{
				label: "Chandelier",
				value: "1",
			},
			{
				label: "Chloroform",
				value: "61",
			},
			{
				label: "Chopsticks",
				value: "4",
			},
			{
				label: "Christmas Lights",
				value: "1",
			},
			{
				label: "Christmas Wrapping Paper",
				value: "23",
			},
			{
				label: "Cigar Cutter",
				value: "5",
			},
			{
				label: "Claymore Mine",
				value: "1",
			},
			{
				label: "Clippers",
				value: "6",
			},
			{
				label: "Clutch",
				value: "14",
			},
			{
				label: "Coat Hanger",
				value: "1",
			},
			{
				label: "Cobra Derringer",
				value: "6",
			},
			{
				label: "Coconut Bra",
				value: "1",
			},
			{
				label: "Coin Purse",
				value: "54",
			},
			{
				label: "Compass",
				value: "44",
			},
			{
				label: "Construction Helmet",
				value: "23",
			},
			{
				label: "Cosmetics Case",
				value: "7",
			},
			{
				label: "Cough Syrup",
				value: "16",
			},
			{
				label: "Crazy Straw",
				value: "128",
			},
			{
				label: "Credit Card",
				value: "14",
			},
			{
				label: "Cricket Bat",
				value: "3",
			},
			{
				label: "Crockpot",
				value: "68",
			},
			{
				label: "Crop Top",
				value: "53",
			},
			{
				label: "Croquet Set",
				value: "1",
			},
			{
				label: "Crossbow",
				value: "4",
			},
			{
				label: "Crowbar",
				value: "24",
			},
			{
				label: "Crucible",
				value: "3",
			},
			{
				label: "Crushed Enamel",
				value: "2",
			},
			{
				label: "Cut-Throat Razor",
				value: "1",
			},
			{
				label: "DVD Player",
				value: "25",
			},
			{
				label: "Dagger",
				value: "59",
			},
			{
				label: "Dart Board",
				value: "8",
			},
			{
				label: "Dental Mirror",
				value: "4",
			},
			{
				label: "Dentures",
				value: "12",
			},
			{
				label: "Desert Eagle",
				value: "8",
			},
			{
				label: "Detergent",
				value: "10",
			},
			{
				label: "Diamond Ring",
				value: "15",
			},
			{
				label: "Diesel",
				value: "140",
			},
			{
				label: "Diving Gloves",
				value: "50",
			},
			{
				label: "Double Cut File",
				value: "1",
			},
			{
				label: "Dozen Roses",
				value: "3",
			},
			{
				label: "Driver's License",
				value: "1",
			},
			{
				label: "Ecstasy",
				value: "53",
			},
			{
				label: "Electronic Pumpkin",
				value: "1",
			},
			{
				label: "Elephant Statue",
				value: "1",
			},
			{
				label: "Embosser",
				value: "4",
			},
			{
				label: "Empty Blood Bag",
				value: "322",
			},
			{
				label: "Empty Box",
				value: "541",
			},
			{
				label: "Epinephrine",
				value: "1",
			},
			{
				label: "Erotic DVD",
				value: "2",
			},
			{
				label: "Family Photo",
				value: "3",
			},
			{
				label: "Fanny Pack",
				value: "1",
			},
			{
				label: "Fertilizer",
				value: "9",
			},
			{
				label: "Festive Socks",
				value: "2",
			},
			{
				label: "Fine Chisel",
				value: "4",
			},
			{
				label: "Fire Extinguisher",
				value: "3",
			},
			{
				label: "Fire Hydrant",
				value: "2",
			},
			{
				label: "Fireworks",
				value: "4",
			},
			{
				label: "First Aid Kit",
				value: "70",
			},
			{
				label: "Fishing Rod",
				value: "20",
			},
			{
				label: "Fiveseven",
				value: "5",
			},
			{
				label: "Flare Gun",
				value: "56",
			},
			{
				label: "Flash Grenade",
				value: "20",
			},
			{
				label: "Flashlight",
				value: "1",
			},
			{
				label: "Flippers",
				value: "44",
			},
			{
				label: "Floor Cleaner",
				value: "34",
			},
			{
				label: "Formaldehyde",
				value: "484",
			},
			{
				label: "Fountain Pen",
				value: "4",
			},
			{
				label: "Fruitcake",
				value: "2",
			},
			{
				label: "Frying Pan",
				value: "3",
			},
			{
				label: "Full Body Armor",
				value: "7",
			},
			{
				label: "Funeral Wreath",
				value: "9",
			},
			{
				label: "Game Console",
				value: "12",
			},
			{
				label: "Garden Gnome",
				value: "19",
			},
			{
				label: "Gasoline",
				value: "36",
			},
			{
				label: "Generic Wrapping Paper",
				value: "10",
			},
			{
				label: "Glock 17",
				value: "38",
			},
			{
				label: "Glow Stick",
				value: "12",
			},
			{
				label: "Glue",
				value: "52",
			},
			{
				label: "Gold Necklace",
				value: "3",
			},
			{
				label: "Gold Ring",
				value: "5",
			},
			{
				label: "Gold Tooth",
				value: "24",
			},
			{
				label: "Gold Watch",
				value: "10",
			},
			{
				label: "Golden Wreath",
				value: "2",
			},
			{
				label: "Golf Club",
				value: "2",
			},
			{
				label: "Grain",
				value: "84",
			},
			{
				label: "Graver",
				value: "1",
			},
			{
				label: "Grenade",
				value: "2",
			},
			{
				label: "Grinding Stone",
				value: "1",
			},
			{
				label: "Guandao",
				value: "65",
			},
			{
				label: "Gym Shorts",
				value: "5",
			},
			{
				label: "HPCPU",
				value: "1",
			},
			{
				label: "Halterneck",
				value: "1",
			},
			{
				label: "Hammer",
				value: "14",
			},
			{
				label: "Hand Drill",
				value: "5",
			},
			{
				label: "Handkerchief",
				value: "38",
			},
			{
				label: "Hard Drive",
				value: "22",
			},
			{
				label: "Harpoon",
				value: "1",
			},
			{
				label: "Headphones",
				value: "2",
			},
			{
				label: "Heckler & Koch SL8",
				value: "3",
			},
			{
				label: "High-Speed Drive",
				value: "1",
			},
			{
				label: "Hiking Boots",
				value: "5",
			},
			{
				label: "Hockey Stick",
				value: "11",
			},
			{
				label: "Hoe",
				value: "7",
			},
			{
				label: "Hole Punch",
				value: "9",
			},
			{
				label: "Horse's Head",
				value: "14",
			},
			{
				label: "Horseshoe",
				value: "369",
			},
			{
				label: "Hot Foil Stamper",
				value: "1",
			},
			{
				label: "Hunting Trophy",
				value: "3",
			},
			{
				label: "Hydrochloric Acid",
				value: "16",
			},
			{
				label: "Ice Pick",
				value: "2",
			},
			{
				label: "Igniter Cord",
				value: "26",
			},
			{
				label: "Inkwell",
				value: "3",
			},
			{
				label: "Ithaca 37",
				value: "2",
			},
			{
				label: "Jacket",
				value: "15",
			},
			{
				label: "Jade Buddha",
				value: "1",
			},
			{
				label: "Jemmy",
				value: "9",
			},
			{
				label: "Jigsaw Puzzle",
				value: "2",
			},
			{
				label: "Kabuki Mask",
				value: "2",
			},
			{
				label: "Kama",
				value: "9",
			},
			{
				label: "Katana",
				value: "3",
			},
			{
				label: "Kerosene",
				value: "1",
			},
			{
				label: "Ketamine",
				value: "460",
			},
			{
				label: "Kevlar Gloves",
				value: "4",
			},
			{
				label: "Kitchen Knife",
				value: "64",
			},
			{
				label: "Kitten Plushie",
				value: "35",
			},
			{
				label: "Knuckle Dusters",
				value: "5",
			},
			{
				label: "LSD",
				value: "122",
			},
			{
				label: "Ladder",
				value: "2",
			},
			{
				label: "Laptop",
				value: "92",
			},
			{
				label: "Latex Gloves",
				value: "1",
			},
			{
				label: "Lawyer's Business Card",
				value: "1",
			},
			{
				label: "Lead Pipe",
				value: "16",
			},
			{
				label: "Leather Boots",
				value: "2",
			},
			{
				label: "Leather Bullwhip",
				value: "3",
			},
			{
				label: "Leather Gloves",
				value: "14",
			},
			{
				label: "Leather Helmet",
				value: "2",
			},
			{
				label: "Leather Vest",
				value: "5",
			},
			{
				label: "Lipstick",
				value: "17",
			},
			{
				label: "Lockpicks",
				value: "6",
			},
			{
				label: "Lollipop",
				value: "14",
			},
			{
				label: "Lottery Voucher",
				value: "1",
			},
			{
				label: "Lubricant",
				value: "12",
			},
			{
				label: "Luger",
				value: "1",
			},
			{
				label: "Lump of Coal",
				value: "100",
			},
			{
				label: "Lye",
				value: "8",
			},
			{
				label: "MP3 Player",
				value: "60",
			},
			{
				label: "Macana",
				value: "2",
			},
			{
				label: "Machine Part",
				value: "115",
			},
			{
				label: "Mag 7",
				value: "1",
			},
			{
				label: "Magazine",
				value: "29",
			},
			{
				label: "Magnesium Shavings",
				value: "4",
			},
			{
				label: "Magnum",
				value: "7",
			},
			{
				label: "Maneki Neko",
				value: "2",
			},
			{
				label: "Massage Oil",
				value: "23",
			},
			{
				label: "Massage Table",
				value: "2",
			},
			{
				label: "Mediocre T-Shirt",
				value: "1",
			},
			{
				label: "Methane Tank",
				value: "356",
			},
			{
				label: "Microwave",
				value: "74",
			},
			{
				label: "Mix CD",
				value: "11",
			},
			{
				label: "Model Space Ship",
				value: "3",
			},
			{
				label: "Model Spine",
				value: "1",
			},
			{
				label: "Mop",
				value: "6",
			},
			{
				label: "Morphine",
				value: "26",
			},
			{
				label: "Mountie Hat",
				value: "2",
			},
			{
				label: "Mouthwash",
				value: "14",
			},
			{
				label: "Net",
				value: "14",
			},
			{
				label: "Ninja Claws",
				value: "1",
			},
			{
				label: "Ninja Star",
				value: "1",
			},
			{
				label: "Nitrous Tank",
				value: "13",
			},
			{
				label: "Nodding Turtle",
				value: "1",
			},
			{
				label: "Notepad",
				value: "126",
			},
			{
				label: "Old Wallet",
				value: "4",
			},
			{
				label: "Opium",
				value: "8",
			},
			{
				label: "Oxygen Tank",
				value: "14",
			},
			{
				label: "PCP",
				value: "2",
			},
			{
				label: "PVC Cards",
				value: "3",
			},
			{
				label: "Pack of Cuban Cigars",
				value: "19",
			},
			{
				label: "Pack of Music CDs",
				value: "5",
			},
			{
				label: "Pantyhose",
				value: "2",
			},
			{
				label: "Paper Towels",
				value: "44",
			},
			{
				label: "Paper Weight",
				value: "1",
			},
			{
				label: "Paperclips",
				value: "4",
			},
			{
				label: "Pearl Necklace",
				value: "15",
			},
			{
				label: "Pele Charm",
				value: "8",
			},
			{
				label: "Pen Knife",
				value: "3",
			},
			{
				label: "Pencil Skirt",
				value: "1",
			},
			{
				label: "Peplum Top",
				value: "5",
			},
			{
				label: "Pepper Spray",
				value: "18",
			},
			{
				label: "Perforator",
				value: "2",
			},
			{
				label: "Perfume",
				value: "29",
			},
			{
				label: "Permanent Marker",
				value: "19",
			},
			{
				label: "Persian Rug",
				value: "1",
			},
			{
				label: "Personal Computer",
				value: "9",
			},
			{
				label: "Phone Card",
				value: "37",
			},
			{
				label: "Phosphorus",
				value: "5",
			},
			{
				label: "Picture Frame",
				value: "47",
			},
			{
				label: "Pillow",
				value: "7",
			},
			{
				label: "Pixie Sticks",
				value: "2",
			},
			{
				label: "Plain Silver Ring",
				value: "60",
			},
			{
				label: "Plastic Watch",
				value: "1",
			},
			{
				label: "Plunger",
				value: "1",
			},
			{
				label: "Polar Bear Toy",
				value: "1",
			},
			{
				label: "Police Vest",
				value: "7",
			},
			{
				label: "Polishing Pad",
				value: "1",
			},
			{
				label: "Polo Shirt",
				value: "20",
			},
			{
				label: "Potassium Nitrate",
				value: "390",
			},
			{
				label: "Printer",
				value: "16",
			},
			{
				label: "Proda Sunglasses",
				value: "2",
			},
			{
				label: "Qsz-92",
				value: "6",
			},
			{
				label: "RS232 Cable",
				value: "20",
			},
			{
				label: "Raw Ivory",
				value: "45",
			},
			{
				label: "Razor Wire",
				value: "20",
			},
			{
				label: "Receipt",
				value: "3",
			},
			{
				label: "Remote Detonator",
				value: "10",
			},
			{
				label: "Rope",
				value: "37",
			},
			{
				label: "Rotten Apple",
				value: "40",
			},
			{
				label: "S&W Revolver",
				value: "1",
			},
			{
				label: "SIG 550",
				value: "2",
			},
			{
				label: "SKS Carbine",
				value: "3",
			},
			{
				label: "Safety Boots",
				value: "26",
			},
			{
				label: "Samurai Sword",
				value: "2",
			},
			{
				label: "Sapphire Ring",
				value: "6",
			},
			{
				label: "Scalp Massager",
				value: "9",
			},
			{
				label: "Scissors",
				value: "9",
			},
			{
				label: "Scrap Metal",
				value: "143",
			},
			{
				label: "Sewing Kit",
				value: "3",
			},
			{
				label: "Sextant",
				value: "43",
			},
			{
				label: "Shampoo",
				value: "78",
			},
			{
				label: "Shaving Foam",
				value: "72",
			},
			{
				label: "Ship in a Bottle",
				value: "4",
			},
			{
				label: "Shorts",
				value: "3",
			},
			{
				label: "Shovel",
				value: "113",
			},
			{
				label: "Silver Bead",
				value: "1",
			},
			{
				label: "Silver Cutlery Set",
				value: "1",
			},
			{
				label: "Silver Necklace",
				value: "3",
			},
			{
				label: "Single Red Rose",
				value: "12",
			},
			{
				label: "Six-Pack of Alcohol",
				value: "5",
			},
			{
				label: "Skeleton Key",
				value: "4",
			},
			{
				label: "Skirt",
				value: "5",
			},
			{
				label: "Slingshot",
				value: "44",
			},
			{
				label: "Small Explosive Device",
				value: "1",
			},
			{
				label: "Small First Aid Kit",
				value: "62",
			},
			{
				label: "Small Suitcase",
				value: "1",
			},
			{
				label: "Smoke Grenade",
				value: "6",
			},
			{
				label: "Snorkel",
				value: "104",
			},
			{
				label: "Snowboard",
				value: "49",
			},
			{
				label: "Soap on a Rope",
				value: "495",
			},
			{
				label: "Soccer Ball",
				value: "67",
			},
			{
				label: "Spear",
				value: "54",
			},
			{
				label: "Speed",
				value: "4",
			},
			{
				label: "Speedo",
				value: "99",
			},
			{
				label: "Spoon",
				value: "4",
			},
			{
				label: "Sports Shades",
				value: "2",
			},
			{
				label: "Spray Paint : Black",
				value: "7",
			},
			{
				label: "Spray Paint : Blue",
				value: "2",
			},
			{
				label: "Spray Paint : Green",
				value: "8",
			},
			{
				label: "Spray Paint : Orange",
				value: "4",
			},
			{
				label: "Spray Paint : Pink",
				value: "67",
			},
			{
				label: "Spray Paint : Purple",
				value: "5",
			},
			{
				label: "Spray Paint : Red",
				value: "69",
			},
			{
				label: "Spray Paint : White",
				value: "64",
			},
			{
				label: "Spy Camera",
				value: "16",
			},
			{
				label: "Stainless Steel Watch",
				value: "10",
			},
			{
				label: "Stamp Collection",
				value: "1",
			},
			{
				label: "Stapler",
				value: "19",
			},
			{
				label: "Stash Box",
				value: "5",
			},
			{
				label: "Steel Drum",
				value: "2",
			},
			{
				label: "Stick of Dynamite",
				value: "47",
			},
			{
				label: "Subway Pass",
				value: "1",
			},
			{
				label: "Sweater",
				value: "2",
			},
			{
				label: "Syringe",
				value: "13",
			},
			{
				label: "Tampon",
				value: "40",
			},
			{
				label: "Tank Top",
				value: "57",
			},
			{
				label: "Taser",
				value: "62",
			},
			{
				label: "Tear Gas",
				value: "40",
			},
			{
				label: "Teddy Bear Plushie",
				value: "6",
			},
			{
				label: "Television",
				value: "13",
			},
			{
				label: "Thimble",
				value: "1",
			},
			{
				label: "Throwing Knife",
				value: "5",
			},
			{
				label: "Tin Can",
				value: "59",
			},
			{
				label: "Tire",
				value: "11",
			},
			{
				label: "Toner",
				value: "29",
			},
			{
				label: "Toothbrush",
				value: "15",
			},
			{
				label: "Toothpaste",
				value: "5",
			},
			{
				label: "Torn City Times",
				value: "71",
			},
			{
				label: "Towel",
				value: "178",
			},
			{
				label: "Tractor Part",
				value: "32",
			},
			{
				label: "Trainers",
				value: "56",
			},
			{
				label: "Travel Mug",
				value: "6",
			},
			{
				label: "Travel Socks",
				value: "2",
			},
			{
				label: "Trout",
				value: "104",
			},
			{
				label: "Truck Nuts",
				value: "1",
			},
			{
				label: "Tumble Dryer",
				value: "1",
			},
			{
				label: "Turkey Baster",
				value: "42",
			},
			{
				label: "Turtleneck",
				value: "5",
			},
			{
				label: "Typewriter",
				value: "5",
			},
			{
				label: "Tyrosine",
				value: "16",
			},
			{
				label: "USP",
				value: "66",
			},
			{
				label: "Umbrella",
				value: "2",
			},
			{
				label: "Urea",
				value: "241",
			},
			{
				label: "Vanity Hand Mirror",
				value: "10",
			},
			{
				label: "Vicodin",
				value: "61",
			},
			{
				label: "Vitamins",
				value: "33",
			},
			{
				label: "WWII Helmet",
				value: "1",
			},
			{
				label: "Wax Seal Stamp",
				value: "2",
			},
			{
				label: "Wetsuit",
				value: "98",
			},
			{
				label: "Wheelbarrow",
				value: "15",
			},
			{
				label: "White Lily",
				value: "1",
			},
			{
				label: "Window Breaker",
				value: "21",
			},
			{
				label: "Windproof Lighter",
				value: "1",
			},
			{
				label: "Wire Cutters",
				value: "7",
			},
			{
				label: "Wrench",
				value: "9",
			},
			{
				label: "Xanax",
				value: "10",
			},
			{
				label: "Yakitori Lantern",
				value: "1",
			},
			{
				label: "Yasukuni Sword",
				value: "1",
			},
			{
				label: "Yoga Pants",
				value: "5",
			},
			{
				label: "Yucca Plant",
				value: "67",
			},
			{
				label: "Zip Wallet",
				value: "62",
			},
		],
		tutorial: null,
		outcome: {
			ID: 10953,
			result: "success",
			special: false,
			story: [
				"Slipping through the side gate, you run around the back of the slaughterhouse undetected.",
				"The door to the rendering area is locked, but you shim it open with your credit card.",
				"It smells like the 1,000-lb sisters' bedsheets in here.",
				"Holding your nose, you wander around, trying to find something worth your time.",
				"There's a shovel and a sack of coal by the furnace.",
				"You decide to make do with this before you pass out from the stench.",
			],
			rewards: [
				{
					type: "items",
					value: [
						{
							id: 707,
							name: "Lump of Coal",
							amount: 1,
						},
						{
							id: 1234,
							name: "Shovel",
							amount: 1,
						},
					],
				},
			],
		},
		user: {
			playername: "DeKleineKobini",
			nerve: 8,
			money: 26421196,
			isAdmin: false,
			isUnderAttack: false,
		},
		time: 1771190457,
	},
};
