---
name: Code Quality Checking

on:
    workflow_dispatch:
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    run-lint:
        runs-on: ubuntu-latest

        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v6

            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Setup Biome
              uses: biomejs/setup-biome@v2

            - name: Run Biome
              run: bun biome ci .
