name: Prepare next version

on:
    workflow_call:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    prepare:
        runs-on: ubuntu-latest
        environment: Release

        steps:
            - uses: actions/checkout@v7
              with:
                  ref: ${{ github.event.repository.default_branch }}

            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Prepare next version metadata
              run: |
                  set -euo pipefail
                  sudo apt-get update
                  sudo apt-get install -y jq moreutils

                  # Setup variables
                  changelogPath="./src/extension/assets/changelog.json"

                  version="$(jq -j ".version" "./package.json")"

                  DaySuffix() {
                    case $(date +%-d) in
                    1|21|31) echo "st";;
                    2|22)    echo "nd";;
                    3|23)    echo "rd";;
                    *)       echo "th";;
                    esac
                  }

                  newVersionMajor="$(echo -n "\"${version}\"" | jq -j "split(\".\")[0] | tonumber | .")"
                  newVersionMinor="$(echo -n "\"${version}\"" | jq -j "split(\".\")[1] | tonumber | .")"
                  newVersionBuild="$(echo -n "\"${version}\"" | jq -j "split(\".\")[2] | tonumber | . + 1")"
                  newVersion="${newVersionMajor}.${newVersionMinor}.${newVersionBuild}"

                  # Export version for future tasks
                  export newVersion
                  echo "newVersion=$newVersion" >> "$GITHUB_ENV"

                  # Add beta changelog entry
                  jq -r --indent 0 "
                    . |=
                      [{
                          \"version\": { \"major\": ${newVersionMajor}, \"minor\": ${newVersionMinor}, \"build\": ${newVersionBuild} },
                          \"title\": \"Beta\",
                          \"date\": false,
                          \"logs\": {
                              \"features\": [],
                              \"fixes\": [],
                              \"changes\": [],
                              \"removed\": [],
                              \"technical\": []
                          }
                      }] +
                      ." "${changelogPath}" | sponge "${changelogPath}"

                  # Change package to next version
                  bun pm version $newVersion --force --no-git-tag-version

            - name: Run Oxfmt
              run: bun oxfmt

            - name: Add & Commit
              uses: EndBug/add-and-commit@v10
              with:
                  message: "Prepare next version: v${{ env.newVersion }}"
