---
name: Testing

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-as-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build as test
        run: bun run build

      - name: Run tests
        run: bun test
